# Generated by Django 5.0.11 on 2026-03-06 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fam', '0001_initial'),
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdelegation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='assetpolicy',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fam.assetpolicy'),
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='assetdelegation',
            name='asset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fam.assetrecord'),
        ),
        migrations.AddField(
            model_name='assetscandetails',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='assettransition',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='famassetbrand',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='famassetmodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fam.famassetbrand'),
        ),
        migrations.AddField(
            model_name='famassetmodel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='famassettype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fam.famassettype'),
        ),
        migrations.AddField(
            model_name='famlabel',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='famlabel',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='assetrecord',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset', to='fam.famlabel'),
        ),
        migrations.AddField(
            model_name='famlabelprintconfiguration',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='labellayout',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='labelprintformat',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
    ]
