# Generated by Django 5.0.11 on 2026-03-06 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('bootstrap_context', models.JSONField(blank=True, default=dict)),
                ('model_config', models.JSONField(blank=True, default=dict)),
                ('tools_config', models.JSONField(blank=True, default=dict)),
                ('targets', models.JSONField(blank=True, default=dict)),
                ('operation_window', models.JSONField(blank=True, default=dict)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('compaction_config', models.JSONField(blank=True, default=dict)),
                ('rate_limits', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('hard_timeout_seconds', models.PositiveIntegerField(default=3600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_robots', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='portal.tenant')),
            ],
            options={
                'db_table': 'robots_robot',
            },
        ),
        migrations.CreateModel(
            name='RobotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=255)),
                ('run_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('intent_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='robots.robot')),
            ],
            options={
                'db_table': 'robots_session',
            },
        ),
        migrations.CreateModel(
            name='RobotRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('trigger_source', models.CharField(default='manual', max_length=100)),
                ('trigger_payload', models.JSONField(blank=True, default=dict)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('execution_context', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_data', models.JSONField(blank=True, default=dict)),
                ('cancel_requested_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot_runs_created', to=settings.AUTH_USER_MODEL)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='robots.robot')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='robots.robotsession')),
            ],
            options={
                'db_table': 'robots_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RobotMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='fact', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='robots.robot')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='robots.robotsession')),
            ],
            options={
                'db_table': 'robots_memory',
            },
        ),
        migrations.CreateModel(
            name='RobotEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='robots.robot')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='robots.robotrun')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='robots.robotsession')),
            ],
            options={
                'db_table': 'robots_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='robot',
            index=models.Index(fields=['tenant', 'enabled'], name='robots_robo_tenant__cdaec9_idx'),
        ),
        migrations.AddIndex(
            model_name='robot',
            index=models.Index(fields=['tenant', 'slug'], name='robots_robo_tenant__688343_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='robot',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='robotsession',
            index=models.Index(fields=['robot', 'updated_at'], name='robots_sess_robot_i_65c250_idx'),
        ),
        migrations.AddIndex(
            model_name='robotsession',
            index=models.Index(fields=['robot', 'run_id'], name='robots_sess_robot_i_f11551_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='robotsession',
            unique_together={('robot', 'session_key')},
        ),
        migrations.AddIndex(
            model_name='robotrun',
            index=models.Index(fields=['robot', 'status'], name='robots_run_robot_i_e2350a_idx'),
        ),
        migrations.AddIndex(
            model_name='robotrun',
            index=models.Index(fields=['robot', '-started_at'], name='robots_run_robot_i_be2fde_idx'),
        ),
        migrations.AddIndex(
            model_name='robotrun',
            index=models.Index(fields=['session', '-started_at'], name='robots_run_session_2d03a6_idx'),
        ),
        migrations.AddIndex(
            model_name='robotmemory',
            index=models.Index(fields=['robot', 'kind', '-created_at'], name='robots_memo_robot_i_47b40f_idx'),
        ),
        migrations.AddIndex(
            model_name='robotmemory',
            index=models.Index(fields=['session', '-created_at'], name='robots_memo_session_5adee3_idx'),
        ),
        migrations.AddIndex(
            model_name='robotevent',
            index=models.Index(fields=['robot', '-created_at'], name='robots_even_robot_i_f83e10_idx'),
        ),
        migrations.AddIndex(
            model_name='robotevent',
            index=models.Index(fields=['run', '-created_at'], name='robots_even_run_id_7775f9_idx'),
        ),
        migrations.AddIndex(
            model_name='robotevent',
            index=models.Index(fields=['event_type', '-created_at'], name='robots_even_event_t_22669c_idx'),
        ),
    ]
