# Generated by Django 5.2.12 on 2026-03-13 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConsoleAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_slug', models.SlugField(default='main', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='Prompt or message sent to the agent')),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('recurring', 'Recurring (schedule)'), ('event', 'Event'), ('webhook', 'Webhook'), ('flow', 'Flow')], default='manual', max_length=32)),
                ('trigger_config', models.JSONField(blank=True, default=dict, help_text='Config for trigger: cron expression, event type, webhook path, flow_id, etc.')),
                ('session_key', models.CharField(blank=True, default='automation', help_text="Session key for the run (e.g. 'automation', 'daily-report')", max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Console Automation',
                'verbose_name_plural': 'Agent Console Automations',
                'db_table': 'agent_console_automation',
            },
        ),
        migrations.CreateModel(
            name='AgentConsoleWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Workspace identifier', max_length=64, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('default_agent_profile_key', models.CharField(blank=True, default='', max_length=64)),
                ('specialty_prompt', models.TextField(blank=True, default='', help_text='Workspace specialization for system prompt')),
                ('default_model', models.CharField(blank=True, default='', max_length=128)),
                ('default_vendor', models.CharField(blank=True, default='', max_length=64)),
                ('default_thinking', models.CharField(blank=True, default='', max_length=32)),
                ('default_verbosity', models.CharField(blank=True, default='', max_length=32)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Agent Console Workspace',
                'verbose_name_plural': 'Agent Console Workspaces',
                'db_table': 'agent_console_workspace',
            },
        ),
        migrations.CreateModel(
            name='AgentConsoleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_slug', models.CharField(db_index=True, max_length=80)),
                ('session_key', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('scope', models.CharField(default='shared', max_length=20)),
                ('owner', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'agent_console_session',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('workspace_slug', 'session_key'), name='agent_console_session_workspace_key_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AgentConsoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Profile key (e.g. default, support)', max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('default_model', models.CharField(blank=True, default='', max_length=128)),
                ('default_vendor', models.CharField(blank=True, default='', max_length=64)),
                ('default_thinking', models.CharField(blank=True, default='', max_length=32)),
                ('default_verbosity', models.CharField(blank=True, default='', max_length=32)),
                ('system_prompt_override', models.TextField(blank=True, default='')),
                ('tool_allowlist', models.JSONField(blank=True, default=list, help_text='List of tool IDs allowed for this profile')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('workspace', models.ForeignKey(blank=True, help_text='Null = tenant-default profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='agent_console.agentconsoleworkspace')),
            ],
            options={
                'verbose_name': 'Agent Console Profile',
                'verbose_name_plural': 'Agent Console Profiles',
                'db_table': 'agent_console_profile',
                'unique_together': {('workspace', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AgentConsolePluginAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(db_index=True, max_length=128)),
                ('user_allowlist', models.JSONField(blank=True, default=list, help_text="List of emails or 'admin' / 'member' for role-based allowlist")),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_assignments', to='agent_console.agentconsoleworkspace')),
            ],
            options={
                'verbose_name': 'Agent Console Plugin Assignment',
                'verbose_name_plural': 'Agent Console Plugin Assignments',
                'db_table': 'agent_console_plugin_assignment',
                'unique_together': {('workspace', 'plugin_id')},
            },
        ),
        migrations.CreateModel(
            name='AgentConsoleWorkspaceSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('body_markdown', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_skills', to='agent_console.agentconsoleworkspace')),
            ],
            options={
                'verbose_name': 'Agent Console Workspace Skill',
                'verbose_name_plural': 'Agent Console Workspace Skills',
                'db_table': 'agent_console_workspace_skill',
                'unique_together': {('workspace', 'skill_id')},
            },
        ),
    ]
