# Generated by Django 5.2.12 on 2026-03-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_console", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentConsoleInstalledPlugin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plugin_id", models.CharField(db_index=True, max_length=128, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("version", models.CharField(blank=True, default="", max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                ("is_platform_approved", models.BooleanField(default=False)),
                ("checksum_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("manifest", models.JSONField(blank=True, default=dict)),
                ("bundle_zip", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent Console Installed Plugin",
                "verbose_name_plural": "Agent Console Installed Plugins",
                "db_table": "agent_console_installed_plugin",
            },
        ),
    ]
