# Generated by Django 5.2.12 on 2026-03-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_console", "0002_agentconsoleinstalledplugin"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconsolepluginassignment",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="agentconsolepluginassignment",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="agentconsolepluginassignment",
            name="plugin_config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
