# Generated by Django 5.2.12 on 2026-03-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('in_app', 'In-app')], db_index=True, max_length=20)),
                ('category', models.CharField(db_index=True, help_text='Notification category e.g. ticket_assigned, flow_completed, deal_won, system_alerts', max_length=80)),
                ('subscribed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User notification preference',
                'verbose_name_plural': 'User notification preferences',
                'db_table': 'notifications_user_notification_preference',
                'ordering': ['user', 'channel', 'category'],
            },
        ),
    ]
