# Generated by Django 5.2.12 on 2026-03-13 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreference',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_preferences', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usernotificationpreference',
            index=models.Index(fields=['user', 'channel'], name='notificatio_user_id_30df9b_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationpreference',
            index=models.Index(fields=['tenant', 'category'], name='notificatio_tenant__3feba7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationpreference',
            unique_together={('user', 'tenant', 'channel', 'category')},
        ),
    ]
