# Generated by Django 5.0.11 on 2026-03-06 17:00

import django.db.models.deletion
import django.utils.timezone
import moio_platform.storage_backends
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=400, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('postal_code', models.CharField(max_length=40, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('document_id', models.CharField(max_length=12)),
                ('work_experience', models.TextField(default='')),
                ('education', models.TextField(default='')),
                ('full_cv_transcript', models.TextField(default='')),
                ('self_summary', models.TextField(default='')),
                ('overall_knowledge', models.TextField(default='')),
                ('distance_to_branches', models.TextField(default='')),
                ('recommended_branch', models.CharField(max_length=200, null=True)),
                ('psicotest_score', models.FloatField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reloaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('recruiter_summary', models.TextField(default='')),
                ('recruiter_posting', models.IntegerField(default=0)),
                ('recruiter_status', models.CharField(choices=[('A', 'Available'), ('M', 'Matches search'), ('P', 'Preselected'), ('D', 'Pending data'), ('C', 'Data is complete'), ('I', 'Invited to group interview'), ('G', 'Confirmed assistance'), ('K', 'Arrived'), ('NS', 'No Show'), ('E', 'Evaluating'), ('EV', 'Evaluated'), ('VP', 'Passed Evaluation'), ('VF', 'Failed Evaluation'), ('O', 'One to one interviews'), ('OI', 'Interviewing'), ('U', 'Unavailable'), ('S', 'Selected'), ('H', 'Hired'), ('R', 'Rejected'), ('W', 'Waiting for data'), ('X', 'Discarded')], default='A', max_length=30)),
                ('source', models.CharField(default='', max_length=40)),
                ('distance_evaluation_done', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(null=True, storage=moio_platform.storage_backends.MediaStorage(), upload_to='profile_pics/')),
                ('code', models.UUIDField(editable=False, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='crm.contact')),
                ('tags', models.ManyToManyField(blank=True, related_name='candidates', to='crm.tag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='CandidateDistances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(blank=True, null=True)),
                ('distance_category', models.CharField(blank=True, max_length=30, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_category', models.CharField(blank=True, max_length=30, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.branch')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=240)),
                ('overall_approve', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateInterviewNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='recruiter.candidateevaluation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=12)),
                ('hired', models.DateField()),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('A', 'active'), ('R', 'resigned'), ('F', 'fired'), ('D', 'deceased'), ('U', 'unknown')], default='A', max_length=100)),
                ('exit', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('rank', models.TextField(default='')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('salary_range', models.TextField(blank=True, max_length=100, null=True)),
                ('embedding', models.TextField(default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant')),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jp_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('N', 'Nuevo'), ('S', 'Confirmar Preselección'), ('I', 'Finalizar Invitaciones'), ('G', 'Iniciar Entrevista Grupal'), ('E', 'Confirmar Evaluaciones'), ('U', 'Finalizar Entrevistas'), ('F', 'Cierre Individuales'), ('C', 'Finalizado')], default='N', max_length=40)),
                ('vacantes', models.IntegerField(default=1)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('closure_date', models.DateTimeField(null=True)),
                ('group_interview_date', models.DateTimeField(blank=True, null=True)),
                ('psigma_link', models.CharField(blank=True, max_length=200, null=True)),
                ('calendar_link', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.IntegerField(blank=True, default=0, null=True)),
                ('invitation_template', models.TextField(default='')),
                ('reminder_template', models.TextField(default='')),
                ('psicotest_template', models.TextField(default='')),
                ('image', models.FileField(blank=True, default='', storage=moio_platform.storage_backends.MediaStorage(), upload_to='images/')),
                ('publish', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('max_age_cv', models.IntegerField(default=60)),
                ('branch', models.ManyToManyField(blank=True, to='crm.branch')),
                ('exclude_tags', models.ManyToManyField(blank=True, related_name='job_postings_refusing', to='crm.tag')),
                ('include_tags', models.ManyToManyField(blank=True, related_name='job_postings_accepting', to='crm.tag')),
                ('job_description', models.ManyToManyField(blank=True, to='recruiter.jobdescription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
            },
        ),
        migrations.CreateModel(
            name='CandidateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_id', models.IntegerField()),
                ('candidate_document', models.CharField(default='', max_length=12, null=True)),
                ('status', models.CharField(default='nuevo', max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruiter.candidate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant')),
                ('job_posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruiter.jobposting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='candidateevaluation',
            name='job_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.jobposting'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='applications',
            field=models.ManyToManyField(to='recruiter.jobposting'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='recruiter.jobposting'),
        ),
        migrations.CreateModel(
            name='RecruiterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiringroom_client_id', models.CharField(default='', max_length=200, null=True)),
                ('hiringroom_client_secret', models.CharField(default='', max_length=200, null=True)),
                ('hiringroom_username', models.CharField(default='', max_length=200, null=True)),
                ('hiringroom_password', models.CharField(default='', max_length=200, null=True)),
                ('psigma_user', models.CharField(default='', max_length=200, null=True)),
                ('psigma_password', models.CharField(default='', max_length=200, null=True)),
                ('psigma_token', models.CharField(default='', max_length=200, null=True)),
                ('psigma_url', models.CharField(default='', max_length=200, null=True)),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecruiterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=moio_platform.storage_backends.MediaStorage(), upload_to='docs/')),
                ('name', models.CharField(max_length=250, null=True)),
                ('read', models.BooleanField(default=False)),
                ('error', models.TextField(default='')),
                ('user', models.CharField(default='', max_length=80, null=True)),
                ('source', models.CharField(default='', max_length=40)),
                ('batch', models.UUIDField(editable=False, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='recruiter_documents', to='crm.tag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant')),
            ],
            options={
                'verbose_name': 'Recruiter_Doc',
            },
        ),
        migrations.CreateModel(
            name='CandidateDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=400, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('postal_code', models.CharField(max_length=40, null=True)),
                ('document_id', models.CharField(max_length=12)),
                ('work_experience', models.TextField(default='')),
                ('education', models.TextField(default='')),
                ('full_cv_transcript', models.TextField(default='')),
                ('self_summary', models.TextField(default='')),
                ('overall_knowledge', models.TextField(default='')),
                ('source', models.CharField(default='', max_length=40)),
                ('profile_picture', models.ImageField(null=True, storage=moio_platform.storage_backends.MediaStorage(), upload_to='profile_pics/')),
                ('tags', models.ManyToManyField(blank=True, related_name='candidate_drafts', to='crm.tag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant')),
                ('cv_file_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruiter.recruiterdocument')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv_file_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruiter.recruiterdocument'),
        ),
        migrations.CreateModel(
            name='CandidateEvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='default', max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('score', models.CharField(max_length=40)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='recruiter.candidateevaluation')),
            ],
            options={
                'unique_together': {('evaluation', 'category')},
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('document_id', 'tenant'), name='employee_unique_documentId_tenant'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('document_id', 'tenant'), name='unique_documentId_tenant'),
        ),
    ]
