# Generated by Django 5.2.12 on 2026-03-13 06:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarAccount',
            fields=[
                ('tenant_uuid', models.UUIDField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
            ],
            options={
                'db_table': 'integration_calendar_account',
            },
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('tenant_uuid', models.UUIDField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inbox', models.CharField(default='INBOX', max_length=255)),
            ],
            options={
                'db_table': 'integration_email_account',
            },
        ),
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('tenant_uuid', models.UUIDField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'google'), ('microsoft', 'microsoft'), ('imap', 'imap')], max_length=20)),
                ('ownership', models.CharField(choices=[('tenant', 'tenant'), ('user', 'user')], max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('credentials', models.JSONField()),
                ('state', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'integration_external_account',
            },
        ),
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('tenant_uuid', models.UUIDField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, help_text="Integration type identifier (e.g., 'whatsapp', 'openai')", max_length=50)),
                ('instance_id', models.CharField(default='default', help_text="Instance identifier for multi-instance integrations (e.g., 'sales', 'support')", max_length=50)),
                ('name', models.CharField(blank=True, default='', help_text='Human-readable name for this integration instance', max_length=100)),
                ('enabled', models.BooleanField(default=False, help_text='Whether this integration is active')),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('invalid_credentials', 'Invalid credentials'), ('uninstalled', 'Uninstalled'), ('pending_link', 'Pending link'), ('disabled', 'Disabled'), ('syncing', 'Syncing')], db_index=True, default='connected', help_text='Canonical binding status (Hub contract)', max_length=32)),
                ('config', models.JSONField(default=dict, help_text='Integration-specific configuration data')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (last_sync, error_count, etc.)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Configuration',
                'verbose_name_plural': 'Integration Configurations',
                'db_table': 'integration_config',
                'ordering': ['slug', 'instance_id'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'platform_plan',
                'ordering': ['display_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PlatformConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('my_url', models.URLField(default='http://127.0.0.1:8000/')),
                ('logo', models.ImageField(blank=True, upload_to='central_hub/')),
                ('favicon', models.ImageField(blank=True, upload_to='central_hub/')),
                ('whatsapp_webhook_token', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('whatsapp_webhook_redirect', models.URLField(default='http://127.0.0.1:8000/')),
                ('fb_system_token', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('fb_moio_bot_app_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fb_moio_business_manager_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fb_moio_bot_app_secret', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fb_moio_bot_configuration_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('google_oauth_client_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('google_oauth_client_secret', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('microsoft_oauth_client_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('microsoft_oauth_client_secret', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('shopify_client_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('shopify_client_secret', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Platform Configuration',
                'verbose_name_plural': 'Platform Configurations',
                'db_table': 'platform_configuration',
            },
        ),
        migrations.CreateModel(
            name='PlatformNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Moio', max_length=200)),
                ('icon_url', models.URLField(blank=True, default='', max_length=500)),
                ('badge_url', models.URLField(blank=True, default='', max_length=500)),
                ('require_interaction', models.BooleanField(default=False)),
                ('renotify', models.BooleanField(default=False)),
                ('silent', models.BooleanField(default=False)),
                ('test_title', models.CharField(blank=True, default='Moio test notification', max_length=200)),
                ('test_body', models.TextField(blank=True, default='Notifications are configured for this browser.')),
            ],
            options={
                'verbose_name': 'Platform notification settings',
                'verbose_name_plural': 'Platform notification settings',
                'db_table': 'platform_notification_settings',
            },
        ),
        migrations.CreateModel(
            name='ShopifyOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=64, unique=True)),
                ('shop_domain', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'shopify_oauth_state',
            },
        ),
        migrations.CreateModel(
            name='ShopifyShopInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('offline_access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('offline_access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, default='')),
                ('api_version', models.CharField(blank=True, default='2025-10', max_length=20)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('uninstalled_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shopify_shop_installation',
            },
        ),
        migrations.CreateModel(
            name='ShopifyShopLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('linked', 'Linked'), ('unlinked', 'Unlinked')], default='linked', max_length=16)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('linked_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('unlinked_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('unlink_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shopify_shop_link',
            },
        ),
        migrations.CreateModel(
            name='ShopifyWebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_domain', models.CharField(db_index=True, max_length=255)),
                ('topic', models.CharField(db_index=True, max_length=64)),
                ('subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('callback_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shopify_webhook_subscription',
            },
        ),
    ]
