# Generated by Django 5.2.12 on 2026-03-13 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('central_hub', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaraccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_calendar_accounts', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_email_accounts', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='externalaccount',
            name='owner_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_external_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_external_accounts', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='external_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='central_hub.externalaccount'),
        ),
        migrations.AddField(
            model_name='calendaraccount',
            name='external_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_accounts', to='central_hub.externalaccount'),
        ),
        migrations.AddField(
            model_name='integrationconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_configs', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='shopifyoauthstate',
            index=models.Index(fields=['state'], name='shopify_oau_state_792cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyoauthstate',
            index=models.Index(fields=['created_at'], name='shopify_oau_created_11fbf0_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyshopinstallation',
            index=models.Index(fields=['shop_domain'], name='shopify_sho_shop_do_74b976_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyshopinstallation',
            index=models.Index(fields=['uninstalled_at'], name='shopify_sho_uninsta_1d17a7_idx'),
        ),
        migrations.AddField(
            model_name='shopifyshoplink',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='central_hub.shopifyshopinstallation'),
        ),
        migrations.AddField(
            model_name='shopifyshoplink',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_shop_links', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='shopifywebhooksubscription',
            index=models.Index(fields=['shop_domain', 'topic'], name='shopify_web_shop_do_97950a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopifywebhooksubscription',
            unique_together={('shop_domain', 'topic')},
        ),
        migrations.AddConstraint(
            model_name='externalaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('ownership', 'user')), fields=('owner_user',), name='external_account_unique_user'),
        ),
        migrations.AddConstraint(
            model_name='externalaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_user__isnull', True), ('ownership', 'tenant')), models.Q(('ownership', 'tenant'), _negated=True), _connector='OR'), name='external_account_tenant_owner_null'),
        ),
        migrations.AddConstraint(
            model_name='externalaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_user__isnull', False), ('ownership', 'user')), models.Q(('ownership', 'user'), _negated=True), _connector='OR'), name='external_account_user_owner_present'),
        ),
        migrations.AddIndex(
            model_name='integrationconfig',
            index=models.Index(fields=['tenant', 'slug'], name='integration_tenant__83bddb_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationconfig',
            index=models.Index(fields=['slug', 'enabled'], name='integration_slug_01f301_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationconfig',
            unique_together={('tenant', 'slug', 'instance_id')},
        ),
        migrations.AddIndex(
            model_name='shopifyshoplink',
            index=models.Index(fields=['shop_domain', 'status'], name='shopify_sho_shop_do_5db91d_idx'),
        ),
        migrations.AddIndex(
            model_name='shopifyshoplink',
            index=models.Index(fields=['tenant', 'status'], name='shopify_sho_tenant__066781_idx'),
        ),
    ]
