# Generated by Django 5.2.12 on 2026-03-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_hub', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfiguration',
            name='organization_locale',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
    ]
