# Generated by Django 5.2.12 on 2026-03-14 22:42

import central_hub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_hub', '0005_plan_self_provision_default_and_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Capability',
                'verbose_name_plural': 'Capabilities',
                'db_table': 'platform_capability',
                'ordering': ['key'],
            },
        ),
        migrations.AlterField(
            model_name='provisioningjob',
            name='stages',
            field=models.JSONField(blank=True, default=central_hub.models.default_provisioning_stages),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('capabilities', models.ManyToManyField(blank=True, help_text='Capabilities granted by this role (intersected with tenant plan).', related_name='roles', to='central_hub.capability')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'platform_role',
                'ordering': ['display_order', 'slug'],
            },
        ),
    ]
