# Generated by Django 5.2.12 on 2026-03-11 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_hub', '0009_integrationconfig_binding_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shopifyoauthstate',
            new_name='shopify_oau_state_792cd1_idx',
            old_name='shopify_oauth_state_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyoauthstate',
            new_name='shopify_oau_created_11fbf0_idx',
            old_name='shopify_oauth_created_idx',
        ),
        migrations.AlterField(
            model_name='shopifyoauthstate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
