# Generated by Django 5.2.12 on 2026-03-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_hub', '0010_rename_shopify_oauth_state_idx_shopify_oau_state_792cd1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyshopinstallation',
            name='offline_access_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopifyshopinstallation',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
