# Generated by Django 5.2.12 on 2026-03-10 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('FORM', 'Form'), ('DIAG', 'Diagnostic'), ('SURV', 'Survey'), ('QUIZ', 'Quiz')], default='FORM', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_enabled', models.BooleanField(default=False)),
                ('llm_assistant_prompt', models.TextField(blank=True)),
                ('llm_content_generation', models.BooleanField(default=False)),
                ('llm_flow_management', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('N', 'Nueva'), ('Q', 'Questions Loop'), ('S1', 'S1 Planned'), ('R', 'Ready'), ('C', 'Completed'), ('X', 'Cancelled')], default='N', max_length=2)),
                ('step', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('answered_questions', models.IntegerField(default=0)),
                ('score', models.JSONField(default=dict)),
                ('insights', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentInstanceResponseVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned', models.BooleanField(default=False)),
                ('mandatory', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('response', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('WEL', 'Welcome'), ('IWO', 'Input With Options'), ('SHI', 'Short Input'), ('LOI', 'Long Input'), ('OPT', 'Options'), ('CON', 'Contact Data'), ('DAT', 'Date Data'), ('SCA', 'Scale Rating'), ('MUL', 'Multiple Choice')], default='SHI', max_length=3)),
                ('configuration', models.JSONField(default=dict)),
                ('question_group', models.IntegerField(default=0)),
                ('optional', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('topic', models.CharField(default='any', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assessment_question_images')),
                ('validation_rules', models.JSONField(default=dict)),
                ('conditional_logic', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=100)),
                ('meaning', models.CharField(default='', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assessment_question_images')),
                ('order', models.IntegerField(default=0)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LLMAssistantConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assistant_id', models.CharField(max_length=100)),
                ('system_prompt', models.TextField()),
                ('content_generation_prompt', models.TextField(blank=True)),
                ('flow_management_prompt', models.TextField(blank=True)),
                ('auto_generate_questions', models.BooleanField(default=False)),
                ('adaptive_questioning', models.BooleanField(default=False)),
                ('real_time_insights', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLMInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('question_generation', 'Question Generation'), ('content_suggestion', 'Content Suggestion'), ('flow_decision', 'Flow Decision'), ('insight_generation', 'Insight Generation'), ('validation', 'Response Validation')], max_length=50)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PainPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
