# Generated by Django 5.0.11 on 2026-03-06 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcampaign',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='assessmentinstance',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_instances', to='assessments.assessmentcampaign'),
        ),
        migrations.AddField(
            model_name='assessmentinstance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentinstanceresponsevector',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessmentinstance'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessmentcampaign'),
        ),
        migrations.AddField(
            model_name='assessmentinstanceresponsevector',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmentquestion'),
        ),
        migrations.AddField(
            model_name='assessmentquestionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.assessmentquestion'),
        ),
        migrations.AddField(
            model_name='llmassistantconfig',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_config', to='assessments.assessmentcampaign'),
        ),
        migrations.AddField(
            model_name='llminteraction',
            name='assessment_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_interactions', to='assessments.assessmentinstance'),
        ),
        migrations.AddField(
            model_name='painpoint',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentcampaign',
            unique_together={('name', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentquestion',
            unique_together={('campaign', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentinstanceresponsevector',
            unique_together={('instance', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentquestionoption',
            unique_together={('question', 'order')},
        ),
    ]
