# Generated by Django 5.2.12 on 2026-03-13 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datalab', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accumulationlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_accumulation_logs', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_analysis_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysismodel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_analysis_models', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='analyzerrun',
            name='analysis_model',
            field=models.ForeignKey(help_text='The Analysis Model that was executed', on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='datalab.analysismodel'),
        ),
        migrations.AddField(
            model_name='analyzerrun',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzer_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyzerrun',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_analyzer_runs', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='crmview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_crm_views', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datalab_created_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_datasets', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datalab_created_dataset_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='dataset',
            field=models.ForeignKey(help_text='Dataset this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='datalab.dataset'),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_dataset_versions', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='current_version',
            field=models.OneToOneField(blank=True, help_text='Current active version (pointer to latest version)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='datalab.datasetversion'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_data_sources', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_file_assets', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='fileasset',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datalab_uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accumulationlog',
            name='processed_files',
            field=models.ManyToManyField(help_text='Files processed in this accumulation', related_name='accumulation_logs', to='datalab.fileasset'),
        ),
        migrations.AddField(
            model_name='fileset',
            name='files',
            field=models.ManyToManyField(related_name='file_sets', to='datalab.fileasset'),
        ),
        migrations.AddField(
            model_name='fileset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_file_sets', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='accumulationlog',
            name='fileset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accumulation_logs', to='datalab.fileset'),
        ),
        migrations.AddField(
            model_name='importprocess',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_import_processes', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='import_process',
            field=models.ForeignKey(help_text='The import process that was executed', on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='datalab.importprocess'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='raw_dataset',
            field=models.ForeignKey(help_text='The file that was processed', on_delete=django.db.models.deletion.CASCADE, related_name='import_runs', to='datalab.fileasset'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_import_runs', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='panel',
            name='analysis_model',
            field=models.ForeignKey(blank=True, help_text='The Analysis Model this panel is bound to. All widgets inherit this binding.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='panels', to='datalab.analysismodel'),
        ),
        migrations.AddField(
            model_name='panel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datalab_panels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='panel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_panels', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='resultset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datalab_created_result_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultset',
            name='dataset_version',
            field=models.OneToOneField(blank=True, help_text='DatasetVersion if this ResultSet was promoted to a dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_set_ref', to='datalab.datasetversion'),
        ),
        migrations.AddField(
            model_name='resultset',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_result_sets', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='result_set',
            field=models.OneToOneField(help_text='ResultSet containing the actual data for this version', on_delete=django.db.models.deletion.CASCADE, related_name='dataset_version_rel', to='datalab.resultset'),
        ),
        migrations.AddField(
            model_name='analyzerrun',
            name='resultset',
            field=models.ForeignKey(blank=True, help_text='The ResultSet produced by this run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzer_runs', to='datalab.resultset'),
        ),
        migrations.AddField(
            model_name='semanticderivation',
            name='import_process',
            field=models.ForeignKey(help_text='The import process this derivation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='semantic_derivations_model', to='datalab.importprocess'),
        ),
        migrations.AddField(
            model_name='semanticderivation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_semantic_derivations', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datalab_created_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='fileset',
            field=models.ForeignKey(blank=True, help_text='FileSet asociado (si este snapshot es resultado de acumulación)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='datalab.fileset'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='resultset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='datalab.resultset'),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_snapshots', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='fileset',
            name='last_snapshot',
            field=models.ForeignKey(blank=True, help_text='Último Snapshot creado para este FileSet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fileset_last_snapshots', to='datalab.snapshot'),
        ),
        migrations.AddField(
            model_name='accumulationlog',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accumulation_logs', to='datalab.snapshot'),
        ),
        migrations.AddField(
            model_name='structuralunit',
            name='import_process',
            field=models.ForeignKey(help_text='The import process this unit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='structural_units_model', to='datalab.importprocess'),
        ),
        migrations.AddField(
            model_name='structuralunit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_structural_units', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='widget',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datalab_widgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='widget',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', related_query_name='widget', to='datalab.panel'),
        ),
        migrations.AddField(
            model_name='widget',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datalab_widgets', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='analysismodel',
            index=models.Index(fields=['tenant', 'name', '-version'], name='datalab_ana_tenant__1bfa3e_idx'),
        ),
        migrations.AddIndex(
            model_name='analysismodel',
            index=models.Index(fields=['tenant', 'is_active', 'is_latest'], name='datalab_ana_tenant__6e34cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analysismodel',
            unique_together={('tenant', 'name', 'version')},
        ),
        migrations.AddIndex(
            model_name='crmview',
            index=models.Index(fields=['tenant', 'key'], name='datalab_crm_tenant__8c47e2_idx'),
        ),
        migrations.AddIndex(
            model_name='crmview',
            index=models.Index(fields=['tenant', 'is_active'], name='datalab_crm_tenant__ea6bab_idx'),
        ),
        migrations.AddIndex(
            model_name='crmview',
            index=models.Index(fields=['is_global', 'is_active'], name='datalab_crm_is_glob_54a84c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crmview',
            unique_together={('tenant', 'key')},
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['tenant', 'name'], name='datalab_dat_tenant__32ae84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['tenant', 'type'], name='datalab_dat_tenant__ed2c88_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['tenant', 'name'], name='datalab_dat_tenant__5914ae_idx'),
        ),
        migrations.AddIndex(
            model_name='datasource',
            index=models.Index(fields=['type', 'ref_id'], name='datalab_dat_type_f97388_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['tenant', 'created_at'], name='datalab_fil_tenant__b77a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='fileasset',
            index=models.Index(fields=['tenant', 'content_type'], name='datalab_fil_tenant__2e414e_idx'),
        ),
        migrations.AddIndex(
            model_name='importprocess',
            index=models.Index(fields=['tenant', 'file_type'], name='datalab_imp_tenant__60eadd_idx'),
        ),
        migrations.AddIndex(
            model_name='importprocess',
            index=models.Index(fields=['tenant', 'shape_fingerprint'], name='datalab_imp_tenant__d51422_idx'),
        ),
        migrations.AddIndex(
            model_name='importprocess',
            index=models.Index(fields=['tenant', 'is_active'], name='datalab_imp_tenant__c25bc9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='importprocess',
            unique_together={('tenant', 'name', 'version')},
        ),
        migrations.AddIndex(
            model_name='importrun',
            index=models.Index(fields=['tenant', 'status'], name='datalab_imp_tenant__4cae56_idx'),
        ),
        migrations.AddIndex(
            model_name='importrun',
            index=models.Index(fields=['import_process', 'created_at'], name='datalab_imp_import__958a96_idx'),
        ),
        migrations.AddIndex(
            model_name='importrun',
            index=models.Index(fields=['raw_dataset'], name='datalab_imp_raw_dat_20a45f_idx'),
        ),
        migrations.AddIndex(
            model_name='panel',
            index=models.Index(fields=['tenant', 'is_public'], name='datalab_pan_tenant__35b5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='panel',
            index=models.Index(fields=['tenant', 'name'], name='datalab_pan_tenant__7de2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='panel',
            index=models.Index(fields=['analysis_model'], name='datalab_pan_analysi_093fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='resultset',
            index=models.Index(fields=['tenant', 'origin'], name='datalab_res_tenant__f8dfc9_idx'),
        ),
        migrations.AddIndex(
            model_name='resultset',
            index=models.Index(fields=['tenant', 'created_at'], name='datalab_res_tenant__1d49b1_idx'),
        ),
        migrations.AddIndex(
            model_name='resultset',
            index=models.Index(fields=['expires_at'], name='datalab_res_expires_c5b265_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetversion',
            index=models.Index(fields=['dataset', 'version_number'], name='datalab_dat_dataset_eb29eb_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetversion',
            index=models.Index(fields=['dataset', 'is_current'], name='datalab_dat_dataset_b393e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datasetversion',
            unique_together={('dataset', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='analyzerrun',
            index=models.Index(fields=['tenant', 'status'], name='datalab_ana_tenant__235b45_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzerrun',
            index=models.Index(fields=['analysis_model', '-created_at'], name='datalab_ana_analysi_f0ba4d_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzerrun',
            index=models.Index(fields=['cache_key'], name='datalab_ana_cache_k_5442f2_idx'),
        ),
        migrations.AddIndex(
            model_name='analyzerrun',
            index=models.Index(fields=['tenant', '-created_at'], name='datalab_ana_tenant__464442_idx'),
        ),
        migrations.AddIndex(
            model_name='semanticderivation',
            index=models.Index(fields=['tenant', 'import_process'], name='datalab_sem_tenant__e46e21_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['tenant', 'name', '-version'], name='datalab_sna_tenant__7a0e83_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['fileset', '-created_at'], name='datalab_sna_fileset_10597c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='snapshot',
            unique_together={('tenant', 'name', 'version')},
        ),
        migrations.AddIndex(
            model_name='fileset',
            index=models.Index(fields=['tenant', 'name'], name='datalab_fil_tenant__48878f_idx'),
        ),
        migrations.AddIndex(
            model_name='accumulationlog',
            index=models.Index(fields=['fileset', '-created_at'], name='datalab_acc_fileset_faf166_idx'),
        ),
        migrations.AddIndex(
            model_name='accumulationlog',
            index=models.Index(fields=['snapshot'], name='datalab_acc_snapsho_2b4268_idx'),
        ),
        migrations.AddIndex(
            model_name='structuralunit',
            index=models.Index(fields=['tenant', 'import_process'], name='datalab_str_tenant__8916ba_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['panel', 'order'], name='datalab_wid_panel_i_3e0ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['tenant', 'widget_type'], name='datalab_wid_tenant__e61a06_idx'),
        ),
    ]
