{{- if or .Values.env.secrets .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moio-frontend.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "moio-frontend.name" . }}
    helm.sh/chart: {{ include "moio-frontend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  {{- range $key, $value := .Values.env.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: |-
{{ $value | nindent 4 }}
  {{- end }}
{{- end }}
