apiVersion: v1
kind: Service
metadata:
  name: {{ include "moio-frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "moio-frontend.name" . }}
    helm.sh/chart: {{ include "moio-frontend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "moio-frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
