# Generated by Django 5.0.11 on 2026-03-06 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chatbot', '0002_initial'),
        ('crm', '0001_initial'),
        ('flows', '0002_initial'),
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycaptureentry',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_captures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitycaptureentry',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AddField(
            model_name='activitycaptureentry',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitycaptureentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_records_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='originating_capture_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_activity_records', to='crm.activitycaptureentry'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_records_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitysuggestion',
            name='activity_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_origin', to='crm.activityrecord'),
        ),
        migrations.AddField(
            model_name='activitysuggestion',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitysuggestion',
            name='capture_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='crm.activitycaptureentry'),
        ),
        migrations.AddField(
            model_name='activitysuggestion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='crm.activitytype'),
        ),
        migrations.AddField(
            model_name='branch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='captureentryauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='captureentryauditevent',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='crm.activitycaptureentry'),
        ),
        migrations.AddField(
            model_name='captureentryauditevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='captureentrylink',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_links', to='crm.activitycaptureentry'),
        ),
        migrations.AddField(
            model_name='captureentrylink',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='company',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='branch',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='linked_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_contacts', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='branch',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='default_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.agentconfiguration'),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='contact',
            name='ctype',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contacttype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_contacts', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_contacts', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='customers', through='crm.CustomerContact', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='customer',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customermetadata'),
        ),
        migrations.AddField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='deal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='deal',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='ecommerceorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='ecommerceorderline',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ecommerceorder'),
        ),
        migrations.AddField(
            model_name='face',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faces', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='face',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='facedetection',
            name='face',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='crm.face'),
        ),
        migrations.AddField(
            model_name='facedetection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='deal',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.pipelinestage'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'VAR'}, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='crm.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='stock',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='crm.tag'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_created', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='origin_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='chatbot.chatbotsession'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='waiting_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_waiting_for', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.ticket'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.ticket'),
        ),
        migrations.AddField(
            model_name='webhookconfig',
            name='linked_flows',
            field=models.ManyToManyField(blank=True, help_text='Flows that this webhook will trigger when called', related_name='webhooks', to='flows.flow'),
        ),
        migrations.AddField(
            model_name='webhookconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='webhookpayload',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payloads', to='crm.webhookconfig'),
        ),
        migrations.AddField(
            model_name='webhookpayload',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddIndex(
            model_name='activitycaptureentry',
            index=models.Index(fields=['tenant', 'anchor_model', 'anchor_id', '-created_at'], name='crm_activit_tenant__a0c48d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitycaptureentry',
            index=models.Index(fields=['tenant', 'actor', '-created_at'], name='crm_activit_tenant__c7f481_idx'),
        ),
        migrations.AddIndex(
            model_name='activitycaptureentry',
            index=models.Index(fields=['tenant', 'status', 'updated_at'], name='crm_activit_tenant__fb0af0_idx'),
        ),
        migrations.AddConstraint(
            model_name='activitycaptureentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('tenant', 'idempotency_key'), name='unique_capture_idempotency_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='activitysuggestion',
            index=models.Index(fields=['status'], name='crm_activit_status_f5c60b_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysuggestion',
            index=models.Index(fields=['assigned_to'], name='crm_activit_assigne_be7334_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysuggestion',
            index=models.Index(fields=['suggested_at'], name='crm_activit_suggest_7f2b4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='activitytype',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='unique_activity_type_key_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='captureentryauditevent',
            index=models.Index(fields=['tenant', 'entry', '-created_at'], name='crm_capture_tenant__4aa9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='captureentryauditevent',
            index=models.Index(fields=['tenant', 'event_type', '-created_at'], name='crm_capture_tenant__4e34b9_idx'),
        ),
        migrations.AddIndex(
            model_name='captureentrylink',
            index=models.Index(fields=['tenant', 'ref_model', 'ref_id'], name='crm_capture_tenant__a7997c_idx'),
        ),
        migrations.AddIndex(
            model_name='captureentrylink',
            index=models.Index(fields=['tenant', 'entry', 'created_at'], name='crm_capture_tenant__098210_idx'),
        ),
        migrations.AddConstraint(
            model_name='contacttype',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_contact_type_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False), models.Q(('phone', ''), _negated=True)), fields=('phone', 'tenant'), name='unique_phone_tenant'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email', 'tenant'), name='unique_email_tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='customercontact',
            unique_together={('customer', 'contact')},
        ),
        migrations.AddConstraint(
            model_name='ecommerceorder',
            constraint=models.UniqueConstraint(fields=('order_number', 'tenant'), name='unique_order_number_tenant'),
        ),
        migrations.AddIndex(
            model_name='face',
            index=models.Index(fields=['last_seen'], name='crm_face_last_se_4ca6a9_idx'),
        ),
        migrations.AddIndex(
            model_name='face',
            index=models.Index(fields=['contact'], name='crm_face_contact_d2f045_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_pipeline_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestage',
            constraint=models.UniqueConstraint(fields=('pipeline', 'name'), name='unique_stage_name_per_pipeline'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['status'], name='crm_deal_status_5e4ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['priority'], name='crm_deal_priorit_383777_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['expected_close_date'], name='crm_deal_expecte_bc08a6_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_at'], name='crm_deal_created_e20d24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'variant_name')},
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'name', 'context'), name='unique_tag_name_context_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'slug', 'context'), name='unique_tag_slug_context_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['kind'], name='crm_activit_kind_28acf9_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['type'], name='crm_activit_type_id_0f9342_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['created_at'], name='crm_activit_created_5860f9_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['status'], name='crm_activit_status_3471fb_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['scheduled_at'], name='crm_activit_schedul_dc269c_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['contact'], name='crm_activit_contact_98ef06_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['owner'], name='crm_activit_owner_i_85f8a3_idx'),
        ),
    ]
