# Generated by Django 5.2.12 on 2026-03-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_trigram_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycaptureentry',
            name='suggested_activities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
