# Generated by Django 5.2.12 on 2026-03-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_shopify_sync_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shopifycustomer',
            new_name='shopify_cus_tenant__5e2d69_idx',
            old_name='crm_shopify_tenant__g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifycustomer',
            new_name='shopify_cus_email_5a4138_idx',
            old_name='crm_shopify_email_j0k1l2_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifycustomer',
            new_name='shopify_cus_last_sy_d58262_idx',
            old_name='crm_shopify_last_sy_m3n4o5_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyorder',
            new_name='shopify_ord_tenant__b79a4d_idx',
            old_name='crm_shopify_tenant__p6q7r8_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyorder',
            new_name='shopify_ord_order_n_04805e_idx',
            old_name='crm_shopify_order_n_s9t0u1_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyorder',
            new_name='shopify_ord_last_sy_206a10_idx',
            old_name='crm_shopify_last_sy_v2w3x4_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyproduct',
            new_name='shopify_pro_tenant__8567e1_idx',
            old_name='crm_shopify_tenant__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifyproduct',
            new_name='shopify_pro_last_sy_b120e9_idx',
            old_name='crm_shopify_last_sy_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifysynclog',
            new_name='shopify_syn_tenant__f2c157_idx',
            old_name='crm_shopify_tenant__y5z6a7_idx',
        ),
        migrations.RenameIndex(
            model_name='shopifysynclog',
            new_name='shopify_syn_status_7d9c34_idx',
            old_name='crm_shopify_status_b8c9d0_idx',
        ),
    ]
