# Generated by Django 5.0.11 on 2026-03-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('fluidcommerce', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedefinition',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='fluidcommerce.attributedefinition'),
        ),
        migrations.AddField(
            model_name='brand',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fluidcommerce.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluidcommerce_orders', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='fluidcommerce.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='fluidcommerce.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='fluidcommerce.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='fluidcommerce.attributedefinition'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='fluidcommerce.product'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_values', to='fluidcommerce.attributeoption'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_options',
            field=models.ManyToManyField(blank=True, related_name='product_multiselect_values', to='fluidcommerce.attributeoption'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='fluidcommerce.product'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='fluidcommerce.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='fluidcommerce.productvariant'),
        ),
        migrations.AddField(
            model_name='orderline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='fluidcommerce.productvariant'),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_values', to='fluidcommerce.attributedefinition'),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_values', to='fluidcommerce.attributeoption'),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='fluidcommerce.productvariant'),
        ),
        migrations.AddIndex(
            model_name='attributedefinition',
            index=models.Index(fields=['tenant', 'is_variant_attribute'], name='fluidcommer_tenant__8fe1bf_idx'),
        ),
        migrations.AddIndex(
            model_name='attributedefinition',
            index=models.Index(fields=['tenant', 'is_filterable'], name='fluidcommer_tenant__45cc24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributedefinition',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='attributeoption',
            index=models.Index(fields=['attribute', 'order'], name='fluidcommer_attribu_19e481_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributeoption',
            unique_together={('attribute', 'value')},
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['tenant', 'is_active'], name='fluidcommer_tenant__59e8dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'is_active'], name='fluidcommer_tenant__4ae56c_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'parent'], name='fluidcommer_tenant__c6c58b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'status'], name='fluidcommer_tenant__b07686_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'payment_status'], name='fluidcommer_tenant__068e92_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'customer_email'], name='fluidcommer_tenant__e92bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'created_at'], name='fluidcommer_tenant__bbde0e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'placed_at'], name='fluidcommer_tenant__ba432f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('tenant', 'order_number')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'status'], name='fluidcommer_tenant__b3e88a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'category'], name='fluidcommer_tenant__13dd28_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'brand'], name='fluidcommer_tenant__432637_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'created_at'], name='fluidcommer_tenant__9b71e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['product', 'attribute'], name='fluidcommer_product_e73a26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['tenant', 'product'], name='fluidcommer_tenant__4b9acf_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['tenant', 'is_active'], name='fluidcommer_tenant__7a5e81_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'position'], name='fluidcommer_product_ac419b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('tenant', 'sku')},
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['product', 'position'], name='fluidcommer_product_d9e74f_idx'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['product', 'is_primary'], name='fluidcommer_product_401210_idx'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['variant', 'position'], name='fluidcommer_variant_192fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['order'], name='fluidcommer_order_i_cb4829_idx'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['variant'], name='fluidcommer_variant_2646d7_idx'),
        ),
        migrations.AddIndex(
            model_name='variantattribute',
            index=models.Index(fields=['variant', 'attribute'], name='fluidcommer_variant_33ddd1_idx'),
        ),
        migrations.AddIndex(
            model_name='variantattribute',
            index=models.Index(fields=['option'], name='fluidcommer_option__ad5c57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variantattribute',
            unique_together={('variant', 'attribute')},
        ),
    ]
