"""Lightweight in-memory flow orchestrator used for synchronous executions."""
from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
import logging
from typing import Any, Callable, Dict, Iterable, List, Mapping, MutableMapping, Optional, Tuple

from .registry import get_executor
from .lib import _now_iso, ISO_TIMESTAMP_FORMAT
from .expressions import FlowExpressionError, eval_sandboxed_expression


logger = logging.getLogger(__name__)


@dataclass
class _Transition:
    """Describe how the execution should continue after a node."""

    target: str
    payload: Any
    target_port: Optional[str]
    source_port: Optional[str]


class FlowRunError(Exception):
    """Error raised when the runtime cannot complete an execution."""

    def __init__(self, message: str, *, node_id: Optional[str] = None) -> None:
        super().__init__(message)
        self.node_id = node_id


class FlowRun:
    """Orchestrate a flow graph in-memory.

    The runtime walks the directed graph generated by the flow builder, executes
    the registered node handlers and records a structured trace of the
    execution. Control-flow nodes (branch, condition, while) are handled by the
    orchestrator itself so expressions are evaluated consistently during tests
    and synchronous previews.
    """

    max_depth: int = 50
    max_steps: int = 500
    max_loop_iterations: int = 100

    def __init__(
        self,
        graph: Mapping[str, Any],
        initial_payload: Optional[Mapping[str, Any]] = None,
        *,
        config: Optional[Mapping[str, Any]] = None,
        tenant_id: Optional[str] = None,
        trigger: Optional[Mapping[str, Any]] = None,
        on_step: Optional[Callable[[Dict[str, Any], int], None]] = None,
        sandbox: bool = False,
        execution_id: Optional[str] = None,
    ) -> None:
        self.graph = graph
        self.initial_payload = dict(initial_payload or {})
        self.sandbox = sandbox
        self.nodes: Dict[str, Mapping[str, Any]] = {
            node["id"]: node for node in graph.get("nodes", [])
        }
        if not self.nodes:
            raise FlowRunError("graph is empty")

        self.edges = list(graph.get("edges", []))
        self.adjacency = self._build_adjacency(self.edges)
        self.inbound = self._build_inbound_index(self.edges)
        self.roots = self._find_roots()

        # Flow runtime contract:
        # - `payload` is the per-node stream (changes at each hop)
        # - `input` is immutable initial trigger input, always available as `input.body`
        body = self.initial_payload if isinstance(self.initial_payload, dict) else {}
        self.context: MutableMapping[str, Any] = {"$input": {"body": body}}
        cfg = dict(config or {}) if isinstance(config, Mapping) else {}
        self.context["config"] = cfg
        if tenant_id:
            self.context["tenant_id"] = tenant_id
        if trigger:
            self.context["$trigger"] = dict(trigger)
            source = str(trigger.get("source") or "").lower()
            if source.startswith("event"):
                # Strict contract: event metadata may exist internally under $trigger,
                # but it is not part of the addressable flow language.
                pass
        if sandbox:
            self.context["$sandbox"] = True
        if execution_id:
            self.context["execution_id"] = execution_id
            self.context["flow_execution_id"] = execution_id
        self.context.setdefault("$outputs", [])
        # Deterministic flow language namespace: nodes.<nodeId>.output.*
        self.context.setdefault("nodes", {})
        self.context.setdefault("$loops", {})
        # Shared CRM last-result namespace (safe to read in Branch/Condition).
        self.context.setdefault("crm", {})

        self.steps: List[Dict[str, Any]] = []
        self.errors: List[Dict[str, Any]] = []
        self._status: str = "pending"
        self._last_error: Optional[Exception] = None
        self._step_counter: int = 0
        self._active_nodes: set[str] = set()
        self._on_step = on_step

    # ------------------------------------------------------------------
    #  Public API
    # ------------------------------------------------------------------
    def execute(self) -> Dict[str, Any]:
        """Execute the graph and return a structured trace."""

        self._status = "running"
        self._assert_input_contract()
        try:
            for root in self.roots:
                self._walk(root["id"], self.initial_payload, incoming_port=None, depth=0)
        except Exception as exc:
            self._status = "failed"
            self._last_error = exc
            raise
        else:
            if self.errors:
                self._status = "failed"
            else:
                self._status = "success"
        return self.snapshot()

    def snapshot(self) -> Dict[str, Any]:
        """Return the latest execution trace without mutating the run."""

        result = {
            "status": self._status,
            "context": self.context,
            "steps": list(self.steps),
            "errors": list(self.errors),
            "outputs": self.context.get("$outputs", []),
        }
        if self._last_error:
            result["last_error"] = {
                "message": str(self._last_error),
                "type": self._last_error.__class__.__name__,
            }
            if isinstance(self._last_error, FlowRunError) and self._last_error.node_id:
                result["last_error"]["node_id"] = self._last_error.node_id
        return result

    # ------------------------------------------------------------------
    #  Internal helpers
    # ------------------------------------------------------------------
    def _walk(
        self,
        node_id: str,
        payload: Any,
        *,
        incoming_port: Optional[str],
        depth: int,
    ) -> Any:
        if self._step_counter >= self.max_steps:
            raise FlowRunError("maximum number of steps exceeded", node_id=node_id)
        if depth > self.max_depth:
            raise FlowRunError("maximum execution depth exceeded", node_id=node_id)
        if node_id in self._active_nodes:
            raise FlowRunError("cycle detected in execution graph", node_id=node_id)

        node = self.nodes.get(node_id)
        if not node:
            raise FlowRunError(f"node '{node_id}' not found", node_id=node_id)

        started = _now_iso()
        step: Dict[str, Any] = {
            "node_id": node_id,
            "kind": node.get("kind"),
            "name": node.get("name"),
            "started_at": started,
            "status": "running",
            "input": payload,
            "incoming_port": incoming_port,
        }

        self._active_nodes.add(node_id)
        try:
            output, transitions, metadata = self._invoke_node(node, payload, depth)
            step["status"] = "success"
            step["output"] = output
            if metadata:
                step["meta"] = metadata
            step["transitions"] = [
                {
                    "target": transition.target,
                    "source_port": transition.source_port,
                    "target_port": transition.target_port,
                }
                for transition in transitions
            ]
        except FlowRunError as exc:
            step["status"] = "error"
            step["error"] = {
                "message": str(exc),
                "type": exc.__class__.__name__,
            }
            if exc.node_id and not step["error"].get("node_id"):
                step["error"]["node_id"] = exc.node_id
            self.errors.append(
                {
                    "node_id": exc.node_id or node_id,
                    "message": str(exc),
                    "type": exc.__class__.__name__,
                }
            )
            raise
        except Exception as exc:  # pragma: no cover - defensive
            wrapped = FlowRunError(str(exc), node_id=node_id)
            step["status"] = "error"
            step["error"] = {
                "message": str(exc),
                "type": exc.__class__.__name__,
            }
            self.errors.append(
                {"node_id": node_id, "message": str(exc), "type": exc.__class__.__name__}
            )
            raise wrapped from exc
        finally:
            step["finished_at"] = _now_iso()
            self.steps.append(step)
            # Contract namespace for downstream placeholders:
            # nodes.<nodeId>.output.* exposes the last output for each executed node.
            nodes_ns = self.context.setdefault("nodes", {})
            if isinstance(nodes_ns, dict):
                nodes_ns[node_id] = {"output": step.get("output")}
            self._step_counter += 1
            self._active_nodes.remove(node_id)

            if self._on_step:
                try:
                    self._on_step(step, len(self.steps))
                except Exception:  # pragma: no cover - defensive
                    logger.exception("step callback failed")

        for transition in transitions:
            self._walk(
                transition.target,
                transition.payload,
                incoming_port=transition.target_port,
                depth=depth + 1,
            )

        return step.get("output")

    def _invoke_node(
        self, node: Mapping[str, Any], payload: Any, depth: int
    ) -> Tuple[Any, List[_Transition], Optional[Dict[str, Any]]]:
        kind = node.get("kind")
        if kind == "logic_branch":
            return self._execute_branch(node, payload)
        if kind == "logic_condition":
            return self._execute_condition(node, payload)
        if kind == "logic_while":
            return self._execute_while(node, payload, depth)

        executor = get_executor(kind)
        try:
            output = executor(node, payload, self.context)
        except Exception as exc:
            raise FlowRunError(str(exc), node_id=node.get("id")) from exc
        transitions = self._next_transitions(node.get("id"), output)
        return output, transitions, None

    # ------------------------------------------------------------------
    #  Control flow implementations
    # ------------------------------------------------------------------
    def _execute_branch(
        self, node: Mapping[str, Any], payload: Any
    ) -> Tuple[Any, List[_Transition], Dict[str, Any]]:
        node_id = node.get("id")
        config = node.get("config", {}) or {}
        rules: Iterable[Mapping[str, Any]] = config.get("rules") or []
        adjacency = self.adjacency.get(node_id, {})

        evaluations: List[Dict[str, Any]] = []
        selected_port: Optional[str] = None

        for index, rule in enumerate(rules):
            name = rule.get("name") or f"rule_{index + 1}"
            expr = rule.get("expr")
            if expr in (None, ""):
                result = True
            else:
                result = bool(self._evaluate_expression(expr, payload, node))
            evaluations.append({"rule": name, "expr": expr, "result": result})
            if result:
                selected_port = name
                break

        if selected_port is None and config.get("else"):
            selected_port = "else"
            evaluations.append({"rule": "else", "expr": None, "result": True})

        transitions: List[_Transition] = []
        if selected_port:
            edges = adjacency.get(selected_port, [])
            transitions = [
                _Transition(
                    target=edge["target"],
                    payload=payload,
                    target_port=edge.get("target_port"),
                    source_port=selected_port,
                )
                for edge in edges
            ]

        output = {"selected": selected_port, "payload": payload}
        metadata = {"selected_port": selected_port, "evaluations": evaluations}
        return output, transitions, metadata

    def _execute_condition(
        self, node: Mapping[str, Any], payload: Any
    ) -> Tuple[Any, List[_Transition], Dict[str, Any]]:
        node_id = node.get("id")
        config = node.get("config", {}) or {}
        expr = config.get("expr")
        if expr in (None, ""):
            result = True
        else:
            result = bool(self._evaluate_expression(expr, payload, node))

        transitions = self._next_transitions(node_id, payload) if result else []
        output = {"result": bool(result), "payload": payload}
        metadata = {"result": bool(result)}
        return output, transitions, metadata

    def _execute_while(
        self, node: Mapping[str, Any], payload: Any, depth: int
    ) -> Tuple[Any, List[_Transition], Dict[str, Any]]:
        node_id = node.get("id")
        config = node.get("config", {}) or {}
        expr = config.get("expr") or "False"
        adjacency = self.adjacency.get(node_id, {})
        yes_edges = adjacency.get("yes", [])
        no_edges = adjacency.get("no", [])

        loop_payload = payload
        history: List[Dict[str, Any]] = []
        iterations = 0
        loop_state = self.context.setdefault("$loops", {})

        while True:
            loop_state[node_id] = iterations
            condition = bool(self._evaluate_expression(expr, loop_payload, node))
            history.append({
                "check": iterations + 1,
                "condition": condition,
                "payload": loop_payload,
            })
            if not condition:
                break

            iterations += 1
            if iterations > self.max_loop_iterations:
                raise FlowRunError(
                    f"while node exceeded {self.max_loop_iterations} iterations",
                    node_id=node_id,
                )

            if not yes_edges:
                break

            for edge in yes_edges:
                loop_payload = self._walk(
                    edge["target"],
                    loop_payload,
                    incoming_port=edge.get("target_port"),
                    depth=depth + 1,
                )

        loop_state[node_id] = iterations
        transitions = [
            _Transition(
                target=edge["target"],
                payload=loop_payload,
                target_port=edge.get("target_port"),
                source_port="no",
            )
            for edge in no_edges
        ]

        output = {"iterations": iterations, "payload": loop_payload}
        metadata = {"iterations": iterations, "checks": history}
        return output, transitions, metadata

    # ------------------------------------------------------------------
    #  Graph utilities
    # ------------------------------------------------------------------
    def _next_transitions(self, node_id: Optional[str], payload: Any) -> List[_Transition]:
        if not node_id:
            return []
        adjacency = self.adjacency.get(node_id, {})
        transitions: List[_Transition] = []
        for port, edges in adjacency.items():
            for edge in edges:
                transitions.append(
                    _Transition(
                        target=edge["target"],
                        payload=payload,
                        target_port=edge.get("target_port"),
                        source_port=port,
                    )
                )
        return transitions

    def _evaluate_expression(self, expr: str, payload: Any, node: Mapping[str, Any]) -> Any:
        # NOTE: Control-flow expressions are sandboxed and declarative.
        # Contract: they can only read `ctx.*`. `payload`/`input` are forbidden here.
        try:
            return eval_sandboxed_expression(expr, ctx=dict(self.context))
        except FlowExpressionError as exc:
            hint = ""
            lowered = (expr or "").lower()
            if "payload" in lowered or "input" in lowered:
                hint = " Expressions can only reference ctx.* (payload/input are not allowed)."
            raise FlowRunError(
                f"error evaluating expression '{expr}': {exc}.{hint}",
                node_id=node.get("id"),
            ) from exc

    def _assert_input_contract(self) -> None:
        """Fail fast if runtime `input` does not match the canonical contract."""

        value = self.context.get("$input")
        if not isinstance(value, dict):
            raise FlowRunError(
                "Invalid flow runtime input contract: expected ctx['$input'] to be a dict with a 'body' key."
            )
        if "body" not in value:
            raise FlowRunError(
                "Invalid flow runtime input contract: expected ctx['$input'] = {'body': ...}."
            )
        if not isinstance(value.get("body"), dict):
            value["body"] = {}

    def _build_adjacency(self, edges: Iterable[Mapping[str, Any]]) -> Dict[str, Dict[str, List[Mapping[str, Any]]]]:
        adjacency: Dict[str, Dict[str, List[Mapping[str, Any]]]] = {}
        for edge in edges:
            source = edge.get("source")
            if not source:
                continue
            port = edge.get("source_port") or "out"
            adjacency.setdefault(source, {}).setdefault(port, []).append(edge)
        return adjacency

    def _build_inbound_index(self, edges: Iterable[Mapping[str, Any]]) -> Dict[str, int]:
        inbound: Dict[str, int] = {}
        for edge in edges:
            target = edge.get("target")
            if target:
                inbound[target] = inbound.get(target, 0) + 1
        return inbound

    def _find_roots(self) -> List[Mapping[str, Any]]:
        triggers = [
            node for node in self.nodes.values() if str(node.get("kind", "")).startswith("trigger_")
        ]
        trigger_roots = [
            node for node in triggers if self.inbound.get(node["id"], 0) == 0
        ]
        if trigger_roots:
            return sorted(trigger_roots, key=lambda item: item["id"])
        if triggers:
            return sorted(triggers, key=lambda item: item["id"])

        roots = [
            node for node in self.nodes.values() if self.inbound.get(node["id"], 0) == 0
        ]
        if roots:
            return sorted(roots, key=lambda item: item["id"])

        # Fallback to deterministic ordering if everything has inbound edges.
        return sorted(self.nodes.values(), key=lambda item: item["id"])


__all__ = ["FlowRun", "FlowRunError"]
