# Generated by Django 5.2.12 on 2026-03-13 06:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('tenant_uuid', models.UUIDField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('static', 'Static list'), ('dynamic', 'Dynamic filter')], default='static', max_length=10)),
                ('rules', models.JSONField(blank=True, null=True)),
                ('size', models.PositiveIntegerField(default=0, editable=False)),
                ('materialized_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudienceMembership',
            fields=[
                ('tenant_uuid', models.UUIDField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('tenant_uuid', models.UUIDField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('sms', 'SMS')], max_length=10)),
                ('kind', models.CharField(choices=[('express', 'Express'), ('one_shot', 'One Shot'), ('drip', 'Drip'), ('planned', 'Planned')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Arbitrary per‑campaign settings (per channel, templates, A/B flags, etc.)')),
                ('sent', models.PositiveIntegerField(default=0)),
                ('opened', models.PositiveIntegerField(default=0)),
                ('responded', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignData',
            fields=[
                ('tenant_uuid', models.UUIDField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variables', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('job', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignDataStaging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_id', models.UUIDField(blank=True, null=True)),
                ('raw_data', models.JSONField()),
                ('mapped_data', models.JSONField(blank=True, null=True)),
                ('import_source', models.CharField(blank=True, default='', max_length=100)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('errors', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
