# Generated by Django 5.0.11 on 2026-03-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('crm', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='audiencemembership',
            name='audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='campaigns.audience'),
        ),
        migrations.AddField(
            model_name='audiencemembership',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_membership', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='audiencemembership',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='audience',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='audiences', through='campaigns.AudienceMembership', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience',
            field=models.ForeignKey(blank=True, help_text='Required before campaign can be activated', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.audience'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='campaigndata',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_rows', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaigndata',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='campaigndatastaging',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_data_staging', to='portal.tenant'),
        ),
        migrations.AddIndex(
            model_name='audiencemembership',
            index=models.Index(fields=['audience'], name='campaigns_a_audienc_2b5f28_idx'),
        ),
        migrations.AddIndex(
            model_name='audiencemembership',
            index=models.Index(fields=['contact'], name='campaigns_a_contact_e350c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='audiencemembership',
            constraint=models.UniqueConstraint(fields=('audience', 'contact'), name='uq_audience_contact_once'),
        ),
        migrations.AddIndex(
            model_name='campaigndata',
            index=models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_4b9ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigndata',
            index=models.Index(fields=['scheduled_at'], name='campaigns_c_schedul_7471ab_idx'),
        ),
    ]
