# Generated by Django 5.2.12 on 2026-03-13 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flows', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='flowagentcontext',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_agent_contexts', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='flowagentturn',
            name='context',
            field=models.ForeignKey(help_text='The parent agent context', on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='flows.flowagentcontext'),
        ),
        migrations.AddField(
            model_name='flowexecution',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='flows.flow'),
        ),
        migrations.AddField(
            model_name='flowagentcontext',
            name='flow_execution',
            field=models.OneToOneField(help_text='The flow execution this context belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='agent_context', to='flows.flowexecution'),
        ),
        migrations.AddField(
            model_name='flowgraphversion',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_versions', to='flows.flow'),
        ),
        migrations.AddField(
            model_name='flowgraphversion',
            name='preview_armed_by',
            field=models.ForeignKey(blank=True, help_text='User who armed this version for preview', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armed_flow_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flowinput',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flowinput',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='flows.flow'),
        ),
        migrations.AddField(
            model_name='flowschedule',
            name='flow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='flows.flow'),
        ),
        migrations.AddField(
            model_name='flowschedule',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_schedules', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='flowscript',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='flows.flow'),
        ),
        migrations.AddField(
            model_name='flowscript',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_scripts', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='flowscriptlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_script_logs', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='flowscriptrun',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='script_runs', to='flows.flow'),
        ),
        migrations.AddField(
            model_name='flowscriptrun',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='flows.flowscript'),
        ),
        migrations.AddField(
            model_name='flowscriptrun',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_script_runs', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='flowscriptlog',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='flows.flowscriptrun'),
        ),
        migrations.AddField(
            model_name='flowscriptversion',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='script_versions', to='flows.flow'),
        ),
        migrations.AddField(
            model_name='flowscriptversion',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='flows.flowscript'),
        ),
        migrations.AddField(
            model_name='flowscriptversion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_script_versions', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='flowscriptrun',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='flows.flowscriptversion'),
        ),
        migrations.AddField(
            model_name='flowsignaltrigger',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_triggers', to='flows.flow'),
        ),
        migrations.AddField(
            model_name='flowsignaltrigger',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_signal_triggers', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='flowversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flow_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flowversion',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='flows.flow'),
        ),
        migrations.AddField(
            model_name='flowversion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_versions', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='flow',
            name='published_version',
            field=models.ForeignKey(blank=True, help_text='Currently published version of this flow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_for_flows', to='flows.flowversion'),
        ),
        migrations.AddField(
            model_name='flowwebhook',
            name='flow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='flows.flow'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='scheduled_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='flows.scheduledtask'),
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='flowagentturn',
            index=models.Index(fields=['context', 'run_index'], name='flows_agent_context_1c652f_idx'),
        ),
        migrations.AddIndex(
            model_name='flowagentturn',
            index=models.Index(fields=['agent_name'], name='flows_agent_agent_n_6fbad0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flowagentturn',
            unique_together={('context', 'run_index')},
        ),
        migrations.AddIndex(
            model_name='flowexecution',
            index=models.Index(fields=['flow', '-started_at'], name='flows_flowe_flow_id_da10c3_idx'),
        ),
        migrations.AddIndex(
            model_name='flowexecution',
            index=models.Index(fields=['flow', 'status'], name='flows_flowe_flow_id_9f7082_idx'),
        ),
        migrations.AddIndex(
            model_name='flowexecution',
            index=models.Index(fields=['-started_at'], name='flows_flowe_started_b4f181_idx'),
        ),
        migrations.AddIndex(
            model_name='flowagentcontext',
            index=models.Index(fields=['tenant', '-started_at'], name='flows_agent_tenant__43ccc3_idx'),
        ),
        migrations.AddIndex(
            model_name='flowagentcontext',
            index=models.Index(fields=['flow_execution'], name='flows_agent_flow_ex_d60d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='flowgraphversion',
            index=models.Index(fields=['flow', 'is_published'], name='flows_flowg_flow_id_2e5260_idx'),
        ),
        migrations.AddIndex(
            model_name='flowgraphversion',
            index=models.Index(fields=['preview_armed'], name='flows_flowg_preview_e0dba9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flowgraphversion',
            unique_together={('flow', 'major', 'minor')},
        ),
        migrations.AlterUniqueTogether(
            name='flowinput',
            unique_together={('flow', 'name')},
        ),
        migrations.AddIndex(
            model_name='flowschedule',
            index=models.Index(fields=['tenant', 'is_active'], name='flows_flows_tenant__331997_idx'),
        ),
        migrations.AddIndex(
            model_name='flowschedule',
            index=models.Index(fields=['flow', 'is_active'], name='flows_flows_flow_id_f5d6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='flowscript',
            index=models.Index(fields=['tenant', 'slug'], name='flows_flows_tenant__9cf6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='flowscript',
            index=models.Index(fields=['tenant', 'flow'], name='flows_flows_tenant__48f6c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flowscript',
            unique_together={('flow', 'slug')},
        ),
        migrations.AddIndex(
            model_name='flowscriptlog',
            index=models.Index(fields=['tenant', 'level'], name='flows_flows_tenant__11e4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='flowscriptlog',
            index=models.Index(fields=['run', '-created_at'], name='flows_flows_run_id_8d387b_idx'),
        ),
        migrations.AddIndex(
            model_name='flowscriptversion',
            index=models.Index(fields=['tenant', 'flow'], name='flows_flows_tenant__0952b9_idx'),
        ),
        migrations.AddIndex(
            model_name='flowscriptversion',
            index=models.Index(fields=['script', '-version_number'], name='flows_flows_script__24b69a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flowscriptversion',
            unique_together={('script', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='flowscriptrun',
            index=models.Index(fields=['tenant', 'flow'], name='flows_flows_tenant__aaa585_idx'),
        ),
        migrations.AddIndex(
            model_name='flowscriptrun',
            index=models.Index(fields=['tenant', 'status'], name='flows_flows_tenant__a73ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='flowscriptrun',
            index=models.Index(fields=['script', '-started_at'], name='flows_flows_script__0474de_idx'),
        ),
        migrations.AddIndex(
            model_name='flowsignaltrigger',
            index=models.Index(fields=['tenant', 'is_active'], name='flows_flows_tenant__37306a_idx'),
        ),
        migrations.AddIndex(
            model_name='flowsignaltrigger',
            index=models.Index(fields=['model_path', 'signal_type', 'is_active'], name='flows_flows_model_p_47f9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='flowsignaltrigger',
            index=models.Index(fields=['flow', 'is_active'], name='flows_flows_flow_id_96716e_idx'),
        ),
        migrations.AddIndex(
            model_name='flowversion',
            index=models.Index(fields=['flow', 'status'], name='flows_flowv_flow_id_69f390_idx'),
        ),
        migrations.AddIndex(
            model_name='flowversion',
            index=models.Index(fields=['flow', '-version'], name='flows_flowv_flow_id_646755_idx'),
        ),
        migrations.AddIndex(
            model_name='flowversion',
            index=models.Index(fields=['tenant', 'status'], name='flows_flowv_tenant__9b1f23_idx'),
        ),
        migrations.AddConstraint(
            model_name='flowversion',
            constraint=models.UniqueConstraint(fields=('flow', 'version'), name='unique_flow_version_number'),
        ),
        migrations.AddConstraint(
            model_name='flowversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'testing')), fields=('flow',), name='one_testing_per_flow'),
        ),
        migrations.AddConstraint(
            model_name='flowversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('flow',), name='one_published_per_flow'),
        ),
        migrations.AddIndex(
            model_name='flow',
            index=models.Index(fields=['tenant', 'status'], name='flows_flow_tenant__821b32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='flowwebhook',
            unique_together={('flow', 'endpoint_path')},
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['tenant', 'is_active'], name='flows_sched_tenant__13ce01_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['tenant', 'status'], name='flows_sched_tenant__2ce2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['task_name'], name='flows_sched_task_na_e7500e_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['scheduled_task', '-started_at'], name='flows_task__schedul_e1baf4_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['tenant', '-started_at'], name='flows_task__tenant__782459_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecution',
            index=models.Index(fields=['status'], name='flows_task__status_6d6713_idx'),
        ),
    ]
