# Generated by Django 5.0.11 on 2026-03-06 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('min_days', models.IntegerField(default=0)),
                ('max_days', models.IntegerField(default=0)),
                ('read_method', models.CharField(blank=True, max_length=40, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('distance_tolerance', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Asset Policies',
                'db_table': 'asset_policy',
            },
        ),
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('last_update', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('last_seen', models.BigIntegerField()),
                ('last_location', models.CharField(max_length=35, null=True)),
                ('last_known_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_known_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('comment', models.TextField(null=True)),
                ('owner_company', models.CharField(blank='True', max_length=255)),
                ('asset_image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('active', models.BooleanField(default=True)),
                ('compliant', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Asset Records',
                'db_table': 'asset_record',
            },
        ),
        migrations.CreateModel(
            name='AssetScanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.IntegerField(blank=True, default=0, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('scanned_by', models.CharField(max_length=35, null=True)),
                ('received_date', models.DateTimeField(null=True)),
                ('full_body', models.JSONField(null=True)),
                ('url', models.URLField(null=True)),
                ('label_id', models.UUIDField(null=True)),
                ('remote_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Scan Details',
                'db_table': 'asset_scan_details',
            },
        ),
        migrations.CreateModel(
            name='AssetTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('trigger', models.CharField(max_length=100, null=True, unique=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('dest', models.CharField(max_length=100, null=True)),
                ('prepare', models.CharField(blank=True, max_length=100, null=True)),
                ('conditions', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Transitions',
                'db_table': 'asset_transition',
            },
        ),
        migrations.CreateModel(
            name='FamAssetBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamAssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=30, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamAssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_tag', models.CharField(default='', max_length=30, unique=True)),
                ('qr_code', models.ImageField(blank=True, editable=False, upload_to='qr_codes/')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamLabelPrintConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('print_template_id', models.CharField(blank=True, default='', max_length=10)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('custom_message', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('show_company_tag', models.BooleanField(default=True)),
                ('show_logo', models.BooleanField(default=False)),
                ('show_custom_message', models.BooleanField(default=False)),
                ('show_mac_address', models.BooleanField(default=False)),
                ('show_creation_date', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabelLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('elements', models.JSONField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='label_logos/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabelPrintFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('layout_key', models.CharField(default='square-center-qr', max_length=64)),
                ('width_mm', models.DecimalField(decimal_places=2, default=60, max_digits=6)),
                ('height_mm', models.DecimalField(decimal_places=2, default=60, max_digits=6)),
                ('dpi', models.PositiveIntegerField(default=300)),
                ('bleed_mm', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('page', models.CharField(default='A4', max_length=12)),
                ('orient', models.CharField(default='portrait', max_length=12)),
                ('cols', models.PositiveIntegerField(default=3)),
                ('rows', models.PositiveIntegerField(default=8)),
                ('cell_w_mm', models.DecimalField(decimal_places=2, default=70, max_digits=6)),
                ('cell_h_mm', models.DecimalField(decimal_places=2, default=37, max_digits=6)),
                ('gap_x_mm', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('gap_y_mm', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('margin_mm', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('main_text', models.CharField(default='Control de Activos', max_length=200)),
                ('code_text', models.CharField(default='{{ code }}', max_length=200)),
                ('sample_code', models.CharField(default='SAMPLE-001', max_length=80)),
                ('mappings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_on', models.DateTimeField(auto_now=True, null=True)),
                ('unassigned_on', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(null=True)),
                ('status', models.CharField(editable=False, max_length=20, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('assigned_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.address')),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
            options={
                'verbose_name_plural': 'Asset Delegations',
                'db_table': 'asset_delegation',
            },
        ),
    ]
