# Generated by Django 5.0.11 on 2026-03-06 17:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(help_text='Service identifier (e.g., fluidland, cms_renderer, webhook_processor)', max_length=100)),
                ('scopes', models.JSONField(blank=True, default=list, help_text='List of allowed scopes (e.g., pages.read, tenant.config.read)')),
                ('tenant_id', models.CharField(blank=True, help_text='Optional tenant restriction. Leave blank for multi-tenant access.', max_length=50, null=True)),
                ('duration_hours', models.PositiveIntegerField(default=24, help_text='Token validity period in hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.TextField(blank=True, help_text='Auto-generated signed JWT token')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Token',
                'verbose_name_plural': 'Service Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
