# Generated by Django 5.2.12

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('last_interaction', models.DateTimeField(auto_now=True, null=True)),
                ('started_by', models.CharField(blank=True, max_length=100, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('final_summary', models.TextField(blank=True, null=True)),
                ('channel', models.CharField(max_length=40, null=True)),
                ('active', models.BooleanField(default=True)),
                ('busy', models.BooleanField(default=False)),
                ('multi_message', models.BooleanField(default=False)),
                ('experience', models.CharField(blank=True, max_length=40, null=True)),
                ('human_mode', models.BooleanField(default=False)),
                ('thread_id', models.CharField(default='', max_length=100)),
                ('assistant_id', models.CharField(default='', max_length=100)),
                ('agent_id', models.UUIDField(blank=True, null=True)),
                ('csat', models.IntegerField(blank=True, null=True)),
                ('current_agent', models.CharField(default='', max_length=100)),
                ('agent_input_thread', models.TextField(null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='crm.contact')),
                ('tenant', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'agent_session',
            },
        ),
        migrations.CreateModel(
            name='SessionThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=45, null=True)),
                ('content', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('intent', models.TextField(null=True)),
                ('subject_of_interest', models.CharField(max_length=200, null=True)),
                ('stitches', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('author', models.CharField(default='', max_length=180)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='chatbot.agentsession')),
            ],
            options={
                'db_table': 'session_thread',
            },
        ),
    ]
