# Generated by Django 5.2.12 on 2026-03-10 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotAssistant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('openai_assistant_id', models.CharField(blank=True, default='', max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('instructions', models.TextField(default='')),
                ('model', models.CharField(max_length=50)),
                ('file_search', models.BooleanField(default=False)),
                ('code_interpreter', models.BooleanField(default=False)),
                ('functions', models.TextField(default='')),
                ('json_object', models.BooleanField(default=False)),
                ('temperature', models.FloatField(default=0)),
                ('top_p', models.FloatField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Assistants',
                'db_table': 'assistant',
            },
        ),
        migrations.CreateModel(
            name='ChatbotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('summarizer_prompt', models.TextField(default='')),
                ('chatbot_prompt', models.TextField(default='')),
                ('experience', models.CharField(default='', max_length=80, unique=True)),
                ('model', models.CharField(default='chat-gpt-4o', max_length=80)),
                ('personality', models.TextField(default='')),
                ('instructions', models.TextField(default='')),
                ('sweeper_instructions', models.TextField(default='')),
                ('channel', models.CharField(default='', max_length=80)),
                ('channel_id', models.CharField(default='', max_length=80)),
            ],
            options={
                'db_table': 'chatbot_configuration',
            },
        ),
        migrations.CreateModel(
            name='ChatbotMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=45, null=True)),
                ('content', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('intent', models.TextField(null=True)),
                ('subject_of_interest', models.CharField(max_length=200, null=True)),
                ('stitches', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('author', models.CharField(default='', max_length=180)),
            ],
            options={
                'db_table': 'chatbot_memory',
            },
        ),
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('session', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(null=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('last_interaction', models.DateTimeField(auto_now=True, null=True)),
                ('started_by', models.CharField(blank=True, max_length=100, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('final_summary', models.TextField(blank=True, null=True)),
                ('channel', models.CharField(max_length=40, null=True)),
                ('active', models.BooleanField(default=True)),
                ('busy', models.BooleanField(default=False)),
                ('multi_message', models.BooleanField(default=False)),
                ('experience', models.CharField(blank=True, max_length=40, null=True)),
                ('human_mode', models.BooleanField(default=False)),
                ('thread_id', models.CharField(default='', max_length=100)),
                ('assistant_id', models.CharField(default='', max_length=100)),
                ('agent_id', models.UUIDField(blank=True, null=True)),
                ('csat', models.IntegerField(blank=True, null=True)),
                ('current_agent', models.CharField(default='', max_length=100)),
                ('agent_input_thread', models.TextField(null=True)),
            ],
            options={
                'db_table': 'chatbot_session',
            },
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('imap_server', models.CharField(max_length=255)),
                ('smtp_server', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('use_ssl', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('ai_assistant_enabled', models.BooleanField(default=False)),
                ('ai_assistant_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('sender', models.EmailField(max_length=254)),
                ('recipients', models.TextField()),
                ('body', models.TextField()),
                ('date_received', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('folder', models.CharField(default='Inbox', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantToolConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_type', models.CharField(choices=[('custom', 'Custom'), ('builtin', 'Built-in')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('custom_description', models.TextField(blank=True)),
                ('custom_display_name', models.CharField(blank=True, max_length=255)),
                ('default_params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant Tool Configuration',
                'verbose_name_plural': 'Tenant Tool Configurations',
                'db_table': 'tenant_tool_configuration',
            },
        ),
        migrations.CreateModel(
            name='WaMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=100, null=True)),
                ('display_phone_number', models.CharField(max_length=100, null=True)),
                ('phone_number_id', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_number', models.CharField(max_length=100, null=True)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('user_message', models.TextField(null=True)),
                ('body', models.TextField(null=True)),
                ('msg_content', models.JSONField(null=True)),
                ('msg_id', models.CharField(max_length=200, null=True)),
                ('context_msg_id', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(db_index=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recipient_id', models.CharField(max_length=100, null=True)),
                ('conversation_id', models.CharField(max_length=200, null=True)),
                ('expiration', models.DateTimeField(null=True)),
                ('origin', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('flow_execution_id', models.UUIDField(blank=True, db_index=True, help_text='Links to FlowExecution for tracing messages sent via flows', null=True)),
                ('api_response', models.JSONField(blank=True, help_text='Full WhatsApp API response from send operation', null=True)),
            ],
            options={
                'db_table': 'wa_message_log',
            },
        ),
        migrations.CreateModel(
            name='WaPayloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_body', models.TextField(null=True)),
                ('timestamp', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
            ],
            options={
                'db_table': 'wa_payloads',
            },
        ),
        migrations.CreateModel(
            name='AgentConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(default='chat-gpt-4o', max_length=80)),
                ('instructions', models.TextField(blank=True, default='', null=True)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('webhook', 'Webhook'), ('desktop', 'Desktop'), ('web', 'Web'), ('flows', 'Flows')], help_text='Select the integration channel for this agent', max_length=80, null=True)),
                ('channel_id', models.CharField(blank=True, max_length=80, null=True)),
                ('tools', models.JSONField(blank=True, default=list, null=True)),
                ('enable_websearch', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default', models.BooleanField(default=False)),
                ('model_settings', models.JSONField(blank=True, default=dict, help_text='JSON representation of the ModelSettings dataclass.')),
                ('handoff_description', models.TextField(blank=True, help_text='Description of handoff behavior and routing logic', null=True)),
                ('guardrails', models.JSONField(blank=True, default=dict, help_text='Guardrail configurations with input/output arrays')),
                ('output', models.JSONField(blank=True, default=dict, help_text='Output configuration including model and format')),
                ('run_behavior', models.JSONField(blank=True, default=dict, help_text='Runtime behavior configuration')),
                ('handoffs', models.ManyToManyField(blank=True, help_text='Agents this agent can hand off to', to='chatbot.agentconfiguration')),
            ],
            options={
                'verbose_name': 'Agent Configuration',
                'verbose_name_plural': 'Agent Configurations',
                'db_table': 'agent_configuration',
            },
        ),
    ]
