# Generated by Django 5.2.12 on 2026-03-10 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        ('crm', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='chatbotassistant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='chatbotconfiguration',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_session', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='chatbotmemory',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_thread', to='chatbot.chatbotsession'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='chatbot.emailaccount'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='tenanttoolconfiguration',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='wamessagelog',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='wapayloads',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='agentconfiguration',
            index=models.Index(fields=['id'], name='agent_confi_id_8818bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('tenant',), name='unique_default_agent_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='agentconfiguration',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_agent_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='chatbotassistant',
            constraint=models.UniqueConstraint(fields=('name', 'tenant'), name='unique_assistant_name_tenant'),
        ),
        migrations.AddIndex(
            model_name='tenanttoolconfiguration',
            index=models.Index(fields=['tenant', 'tool_name'], name='tenant_tool_tenant__3ad67c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenanttoolconfiguration',
            unique_together={('tenant', 'tool_name')},
        ),
        migrations.AddIndex(
            model_name='wamessagelog',
            index=models.Index(fields=['tenant', 'created'], name='wa_log_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='wamessagelog',
            index=models.Index(fields=['tenant', 'status'], name='wa_log_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='wamessagelog',
            index=models.Index(fields=['flow_execution_id'], name='wa_log_flow_exec_idx'),
        ),
    ]
