# Generated by Django 5.0.11 on 2026-03-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watemplate",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="watemplatecomponent",
            name="template",
        ),
        migrations.RemoveField(
            model_name="watemplatecomponent",
            name="tenant",
        ),
        migrations.DeleteModel(
            name="OpenaiConfiguration",
        ),
        migrations.DeleteModel(
            name="WaTemplate",
        ),
        migrations.DeleteModel(
            name="WaTemplateComponent",
        ),
    ]
