# Generated by Django 5.2.12 on 2026-03-13 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_agentsession_tenant_uuid_chatbotconfiguration_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotAssistant',
            fields=[
                ('tenant_uuid', models.UUIDField(db_index=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('openai_assistant_id', models.CharField(blank=True, default='', max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('instructions', models.TextField(default='')),
                ('model', models.CharField(max_length=50)),
                ('file_search', models.BooleanField(default=False)),
                ('code_interpreter', models.BooleanField(default=False)),
                ('functions', models.TextField(default='')),
                ('json_object', models.BooleanField(default=False)),
                ('temperature', models.FloatField(default=0)),
                ('top_p', models.FloatField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'Assistants',
                'db_table': 'assistant',
                'constraints': [models.UniqueConstraint(fields=('name', 'tenant'), name='unique_assistant_name_tenant')],
            },
        ),
    ]
