# Generated by Django 5.2.12 on 2026-03-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_tenant_chatbot_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentconfiguration',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('webhook', 'Webhook'), ('desktop', 'Desktop'), ('web', 'Web'), ('flows', 'Flows'), ('shopify_webchat', 'Shopify Webchat')], help_text='Select the integration channel for this agent', max_length=80, null=True),
        ),
    ]
