# Generated by Django 5.0.11 on 2026-03-06 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('landing_api', '0001_initial'),
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='landing_api.articlecategory'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_categories', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='landing_api.articlecategory'),
        ),
        migrations.AddField(
            model_name='articletag',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tags', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='landing_api.articletag'),
        ),
        migrations.AddField(
            model_name='blockbundle',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Owner tenant for non-global bundles. Null for global bundles.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_bundles', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='blockbundleversion',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='landing_api.blockbundle'),
        ),
        migrations.AddField(
            model_name='blockbundleversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_bundle_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockdefinition',
            name='bundle_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_definitions', to='landing_api.blockbundleversion'),
        ),
        migrations.AddField(
            model_name='bundleinstall',
            name='bundle_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='landing_api.blockbundleversion'),
        ),
        migrations.AddField(
            model_name='bundleinstall',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bundleinstall',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_installs', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='landing_api.conversation'),
        ),
        migrations.AddField(
            model_name='fluidblock',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_blocks', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='fluidmedia',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_media', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_articles', to='landing_api.fluidmedia'),
        ),
        migrations.AddField(
            model_name='fluidpage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_pages', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='fluidblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='landing_api.fluidpage'),
        ),
        migrations.AddField(
            model_name='like',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='landing_api.conversationmessage'),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='landing_api.fluidpage'),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_page_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_versions', to='portal.tenant'),
        ),
        migrations.AddField(
            model_name='like',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to='landing_api.topic'),
        ),
        migrations.AddField(
            model_name='conversationturn',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_turns', to='landing_api.topic'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_messages', to='landing_api.topic'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='landing_api.topic'),
        ),
        migrations.AddField(
            model_name='topicvisit',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='landing_api.topic'),
        ),
        migrations.AddField(
            model_name='visitorsession',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_sessions', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='topicvisit',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_visits', to='landing_api.visitorsession'),
        ),
        migrations.AddField(
            model_name='meetingbooking',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='landing_api.visitorsession'),
        ),
        migrations.AddField(
            model_name='like',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='landing_api.visitorsession'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='landing_api.visitorsession'),
        ),
        migrations.AddField(
            model_name='conversationturn',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_turns', to='landing_api.visitorsession'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='landing_api.visitorsession'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='landing_api.visitorsession'),
        ),
        migrations.AddField(
            model_name='whatsapplog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='landing_api.visitorsession'),
        ),
        migrations.AddIndex(
            model_name='articlecategory',
            index=models.Index(fields=['tenant', 'slug'], name='landing_api_tenant__71a138_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecategory',
            index=models.Index(fields=['tenant', 'is_active'], name='landing_api_tenant__98ad67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articlecategory',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='articletag',
            index=models.Index(fields=['tenant', 'slug'], name='landing_api_tenant__09df41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articletag',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='blockbundle',
            index=models.Index(fields=['slug'], name='landing_api_slug_51d284_idx'),
        ),
        migrations.AddIndex(
            model_name='blockbundle',
            index=models.Index(fields=['is_global'], name='landing_api_is_glob_ff112a_idx'),
        ),
        migrations.AddIndex(
            model_name='blockbundle',
            index=models.Index(fields=['tenant'], name='landing_api_tenant__18cd76_idx'),
        ),
        migrations.AddIndex(
            model_name='blockbundleversion',
            index=models.Index(fields=['bundle', 'status'], name='landing_api_bundle__c653d6_idx'),
        ),
        migrations.AddIndex(
            model_name='blockbundleversion',
            index=models.Index(fields=['bundle', 'version'], name='landing_api_bundle__d1726d_idx'),
        ),
        migrations.AddIndex(
            model_name='blockbundleversion',
            index=models.Index(fields=['status'], name='landing_api_status_3f211b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockbundleversion',
            unique_together={('bundle', 'version')},
        ),
        migrations.AddIndex(
            model_name='blockdefinition',
            index=models.Index(fields=['bundle_version', 'block_type_id'], name='landing_api_bundle__4cfe38_idx'),
        ),
        migrations.AddIndex(
            model_name='blockdefinition',
            index=models.Index(fields=['bundle_version', 'category'], name='landing_api_bundle__11f6ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockdefinition',
            unique_together={('bundle_version', 'block_type_id')},
        ),
        migrations.AddIndex(
            model_name='bundleinstall',
            index=models.Index(fields=['tenant', 'status'], name='landing_api_tenant__839246_idx'),
        ),
        migrations.AddIndex(
            model_name='bundleinstall',
            index=models.Index(fields=['tenant', 'bundle_version'], name='landing_api_tenant__cc7465_idx'),
        ),
        migrations.AddIndex(
            model_name='fluidmedia',
            index=models.Index(fields=['tenant', 'type'], name='landing_api_tenant__2826df_idx'),
        ),
        migrations.AddIndex(
            model_name='fluidmedia',
            index=models.Index(fields=['tenant', 'created_at'], name='landing_api_tenant__21d2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['tenant', 'slug'], name='landing_api_tenant__5bd144_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['tenant', 'status'], name='landing_api_tenant__364e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['tenant', 'published_at'], name='landing_api_tenant__ed2f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['tenant', 'category'], name='landing_api_tenant__852293_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='fluidpage',
            index=models.Index(fields=['tenant', 'slug'], name='landing_api_tenant__2a37d6_idx'),
        ),
        migrations.AddIndex(
            model_name='fluidpage',
            index=models.Index(fields=['tenant', 'is_home'], name='landing_api_tenant__c20eb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fluidpage',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AddIndex(
            model_name='fluidblock',
            index=models.Index(fields=['page', 'order'], name='landing_api_page_id_3a6c87_idx'),
        ),
        migrations.AddIndex(
            model_name='fluidblock',
            index=models.Index(fields=['page', 'key', 'locale'], name='landing_api_page_id_8caa41_idx'),
        ),
        migrations.AddIndex(
            model_name='fluidblock',
            index=models.Index(fields=['tenant', 'is_active'], name='landing_api_tenant__a7ede4_idx'),
        ),
        migrations.AddIndex(
            model_name='pageversion',
            index=models.Index(fields=['page', 'version_number'], name='landing_api_page_id_ae56ea_idx'),
        ),
        migrations.AddIndex(
            model_name='pageversion',
            index=models.Index(fields=['tenant', 'published_at'], name='landing_api_tenant__cf8407_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pageversion',
            unique_together={('page', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('session', 'message_index')},
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['session', 'created_at'], name='landing_api_session_fa3ced_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='landing_api_convers_c8b75a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['session', 'topic', 'created_at'], name='landing_api_session_d21564_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversationmessage',
            unique_together={('conversation', 'conversation_sequence'), ('session', 'session_sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('session', 'topic', 'conversation_date')},
        ),
    ]
