{{- if .Values.pgbouncer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: {{ .Release.Namespace }}
  labels:
    app: pgbouncer
spec:
  replicas: {{ .Values.pgbouncer.replicas }}
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: {{ .Values.pgbouncer.image.repository }}:{{ .Values.pgbouncer.image.tag }}
          imagePullPolicy: {{ .Values.pgbouncer.image.pullPolicy }}
          ports:
            - name: pgbouncer
              containerPort: 6432
          volumeMounts:
            - name: config
              mountPath: /etc/pgbouncer
              readOnly: true
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: pgbouncer-config
              - secret:
                  name: pgbouncer-auth
{{- end }}
