apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    app: scheduler
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: scheduler
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - celery
            - -A
            - moio_platform
            - beat
            - --scheduler
            - django_celery_beat.schedulers:DatabaseScheduler
          env:
            - name: IMAGE_TAG
              value: {{ .Values.image.tag | quote }}
          envFrom:
            - configMapRef:
                name: moio-greenfield-config
            - secretRef:
                name: moio-greenfield-secrets
