apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-low
  namespace: {{ .Release.Namespace }}
  labels:
    app: worker-low
spec:
  replicas: {{ .Values.workers.low.replicas }}
  selector:
    matchLabels:
      app: worker-low
  template:
    metadata:
      labels:
        app: worker-low
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: worker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - "/bin/sh"
            - "-c"
            - "celery -A moio_platform worker -E -l info --concurrency={{ .Values.workers.low.concurrency }} -Q ${APP_NAME}-LOW"
          env:
            - name: IMAGE_TAG
              value: {{ .Values.image.tag | quote }}
          envFrom:
            - configMapRef:
                name: moio-greenfield-config
            - secretRef:
                name: moio-greenfield-secrets
