{{- if .Values.pgbouncer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pgbouncer-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  # format for auth_type=plain: "username" "password"
  userlist.txt: |
    "{{ .Values.pgbouncer.auth.user }}" "{{ .Values.pgbouncer.auth.password }}"
{{- end }}
