apiVersion: v1
kind: Secret
metadata:
  name: moio-greenfield-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secret_key | quote }}
  OTHER_SECRET: {{ .Values.secrets.other_secret | quote }}
