{{- if .Values.pgbouncer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: pgbouncer
  ports:
    - name: pgbouncer
      port: 6432
      targetPort: 6432
{{- end }}
