{{- if .Values.pushpin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pushpin-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: pushpin
  ports:
    - name: http
      port: {{ .Values.pushpin.servicePort }}
      targetPort: 80
{{- end }}
