# Generated by Django 5.0.11 on 2026-03-06 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEndpointNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.CharField(db_index=True, max_length=200)),
                ('note_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('tip', 'Tip'), ('deprecated', 'Deprecated')], default='info', max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['operation_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GuideCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Icon name (e.g., 'book', 'code')", max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Guide Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CodeExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.CharField(db_index=True, help_text='OpenAPI operationId', max_length=200)),
                ('language', models.CharField(choices=[('curl', 'cURL'), ('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('nodejs', 'Node.js'), ('php', 'PHP'), ('ruby', 'Ruby'), ('go', 'Go'), ('java', 'Java'), ('csharp', 'C#')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['operation_id', 'order'],
                'unique_together': {('operation_id', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(blank=True, help_text='Short description for listings')),
                ('content', models.TextField(help_text='Markdown content')),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='docs_api.guidecategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'title'],
            },
        ),
    ]
