# Generated by Django 5.2.12 on 2026-03-13 06:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('base_url', models.URLField(blank=True, default='')),
                ('openapi_url', models.URLField(blank=True, default='')),
                ('default_auth_type', models.CharField(choices=[('none', 'No authentication'), ('bearer', 'Bearer token'), ('api_key_header', 'API key header'), ('api_key_query', 'API key query'), ('basic', 'Basic auth'), ('oauth2_client_credentials', 'OAuth2 client credentials')], default='bearer', max_length=30)),
                ('auth_scope', models.CharField(choices=[('global', 'Global credentials'), ('tenant', 'Tenant credentials'), ('user', 'User credentials')], default='tenant', max_length=20)),
                ('auth_config_schema', models.JSONField(blank=True, default=dict)),
                ('global_auth_config', models.JSONField(blank=True, default=dict)),
                ('assistant_docs_markdown', models.TextField(blank=True, default='')),
                ('default_headers', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenancy_integration_definition',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(blank=True, db_index=True, max_length=63, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('enabled', models.BooleanField(default=True)),
                ('domain', models.CharField(max_length=150)),
                ('subdomain', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('plan', models.CharField(default='free', max_length=40)),
                ('tenant_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('features', models.JSONField(blank=True, default=dict, help_text='Feature flags e.g. {crm_contacts_read: true, users_manage: false}')),
                ('limits', models.JSONField(blank=True, default=dict, help_text='Limits e.g. {seats: 5, agents: 2, flows: 20}')),
                ('ui', models.JSONField(blank=True, default=dict, help_text='Optional UI hints for frontend')),
                ('entitlements_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('organization_locale', models.CharField(blank=True, default='en', max_length=10)),
                ('organization_currency', models.CharField(default='USD', max_length=3)),
                ('organization_timezone', models.CharField(default='UTC', max_length=100)),
                ('organization_date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('organization_time_format', models.CharField(default='24h', max_length=10)),
                ('default_notification_list', models.TextField(blank=True, default='martin@moio.ai,', null=True)),
            ],
            options={
                'db_table': 'portal_tenant',
            },
        ),
        migrations.CreateModel(
            name='MoioUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('avatar', models.ImageField(default='avatars/default-avatar.png', upload_to='avatars/')),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('groups', models.ManyToManyField(blank=True, related_name='moiouser_set', related_query_name='moiouser', to='auth.group', verbose_name='groups')),
                ('reports_to', models.ManyToManyField(blank=True, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='moiouser_set', related_query_name='moiouser', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tenancy_moiouser',
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=255, unique=True)),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenancy_auth_session',
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'Tenant domain',
                'verbose_name_plural': 'Tenant domains',
                'db_table': 'portal_tenant_domain',
            },
        ),
        migrations.CreateModel(
            name='UserApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(default='API Key', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User API Key',
                'verbose_name_plural': 'User API Keys',
                'db_table': 'tenancy_userapikey',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('locale', models.CharField(blank=True, default='en', max_length=20)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=60)),
                ('onboarding_state', models.CharField(blank=True, default='pending', max_length=50)),
                ('default_landing', models.CharField(blank=True, default='/dashboard', max_length=200)),
                ('ui_preferences', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
                'db_table': 'tenancy_user_profile',
            },
        ),
        migrations.CreateModel(
            name='TenantIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('assistant_docs_override', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('tenant_auth_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_bindings', to='tenancy.integrationdefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_bindings', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tenancy_tenant_integration',
                'ordering': ['tenant_id', 'integration_id'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'integration'), name='tenancy_uq_tenant_integration')],
            },
        ),
    ]
