# Generated by Django 5.2.12 on 2026-03-10 21:20

from django.conf import settings
from django.db import migrations, models


def migrate_reports_to_fk_to_m2m(apps, schema_editor):
    """Copy existing reports_to FK data into the new M2M before removing FK."""
    MoioUser = apps.get_model("tenancy", "MoioUser")
    for user in MoioUser.objects.filter(reports_to_old__isnull=False).select_related("reports_to_old"):
        user.reports_to.add(user.reports_to_old)


def reverse_migrate(apps, schema_editor):
    """On reverse: set reports_to_old to first manager in M2M (best-effort)."""
    MoioUser = apps.get_model("tenancy", "MoioUser")
    for user in MoioUser.objects.prefetch_related("reports_to"):
        managers = list(user.reports_to.all()[:1])
        if managers:
            user.reports_to_old_id = managers[0].pk
            user.save(update_fields=["reports_to_old_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0002_add_reports_to"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moiouser",
            old_name="reports_to",
            new_name="reports_to_old",
        ),
        migrations.AddField(
            model_name="moiouser",
            name="reports_to",
            field=models.ManyToManyField(blank=True, related_name="direct_reports", to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_reports_to_fk_to_m2m, reverse_migrate),
        migrations.RemoveField(
            model_name="moiouser",
            name="reports_to_old",
        ),
    ]
