# Generated by Django 5.2.12 on 2026-03-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_reports_to_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_notification_list',
            field=models.TextField(blank=True, default='martin@moio.ai,', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='organization_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='tenant',
            name='organization_date_format',
            field=models.CharField(default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='organization_locale',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='organization_time_format',
            field=models.CharField(default='24h', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='organization_timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
